
/****************************************************************************
 *  (c) Copyright 2007 Wi-Fi Alliance.  All Rights Reserved
 *
 *
 *  LICENSE
 *
 *  License is granted only to Wi-Fi Alliance members and designated
 *  contractors (“Authorized Licensees”).  Authorized Licensees are granted
 *  the non-exclusive, worldwide, limited right to use, copy, import, export
 *  and distribute this software:
 *  (i) solely for noncommercial applications and solely for testing Wi-Fi
 *  equipment; and
 *  (ii) solely for the purpose of embedding the software into Authorized
 *  Licensee’s proprietary equipment and software products for distribution to
 *  its customers under a license with at least the same restrictions as
 *  contained in this License, including, without limitation, the disclaimer of
 *  warranty and limitation of liability, below.  The distribution rights
 *  granted in clause
 *  (ii), above, include distribution to third party companies who will
 *  redistribute the Authorized Licensee’s product to their customers with or
 *  without such third party’s private label. Other than expressly granted
 *  herein, this License is not transferable or sublicensable, and it does not
 *  extend to and may not be used with non-Wi-Fi applications.  Wi-Fi Alliance
 *  reserves all rights not expressly granted herein. 
 * 
 *  Except as specifically set forth above, commercial derivative works of
 *  this software or applications that use the Wi-Fi scripts generated by this
 *  software are NOT AUTHORIZED without specific prior written permission from
 *  Wi-Fi Alliance.
 * 
 *  Non-Commercial derivative works of this software for internal use are
 *  authorized and are limited by the same restrictions; provided, however,
 *  that the Authorized Licensee shall provide Wi-Fi Alliance with a copy of
 *  such derivative works under a perpetual, payment-free license to use,
 *  modify, and distribute such derivative works for purposes of testing Wi-Fi
 *  equipment.
 * 
 *  Neither the name of the author nor "Wi-Fi Alliance" may be used to endorse
 *  or promote products that are derived from or that use this software without
 *  specific prior written permission from Wi-Fi Alliance.
 *
 *  THIS SOFTWARE IS PROVIDED BY WI-FI ALLIANCE "AS IS" AND ANY EXPRESS OR
 *  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE,
 *  ARE DISCLAIMED. IN NO EVENT SHALL WI-FI ALLIANCE BE LIABLE FOR ANY DIRECT,
 *  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *  (INCLUDING, BUT NOT LIMITED TO, THE COST OF PROCUREMENT OF SUBSTITUTE
 *  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 *  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 *  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE) ARISING IN ANY WAY OUT OF
 *  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. ******************************************************************************
 */
/*
 * File: wfa_cmdtbl.c 
 *   The file contains a predefined function array. The command process and
 *   execution functions of a DUT traffic generator and control will be 
 *   registered in the array/table by the order of the defined commands TLV  
 *   values.
 *
 *   Revision History:
 *      2006/03/10 -- initially created by qhu
 *      2006/06/01 -- BETA release by qhu
 *      2006/06/13 -- 00.02 release by qhu
 *      2006/06/30 -- 00.10 Release by qhu
 *      2006/07/10 -- 01.00 Release by qhu
 *      2006/09/01 -- 01.05 Release by qhu
 *      2007/02/15  -- WMM Extension Beta released by qhu, mkaroshi
 *      2007/03/30 -- 01.40 WPA2 and Official WMM Beta release by qhu
 *      2007/04/20 -- 02.00 WPA2 and Official WMM release by qhu
 *      2007/08/15 --  02.10 WMM-Power Save release by qhu
 *      2007/10/10 --  02.20 Voice SOHO beta -- qhu
 *      2007/11/07 --  02.30 Voice HSO -- qhu
 *      2007/12/10 --  02.32 Add a function to upload test results.
 *
 *      2014/01/10 --  8.01-001 PMF Add TLV functions -- OG
 *                     -WFA_AP_SET_PMF_TLV
 *                     -WFA_AP_GET_MAC_ADDRESS_TLV
 *                     -WFA_AP_DEAUTH_STA_TLV
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
//#include <sys/socket.h>
#include "wfa_debug.h"
#include "wfa_types.h"
#include "wfa_main.h"
#include "wfa_tlv.h"
#include "wfa_tg.h"
#include "wfa_miscs.h"
#include "wfa_ca.h"
#include "wfa_sock.h"
#include "wfa_agt.h"
#include "wfa_rsp.h"

int NotDefinedYet(int len, unsigned char *params, int *respLen, BYTE *respBuf);
extern int agtCmdProcGetVersion(int len, BYTE *parms, int *respLen, BYTE *respBuf);

extern unsigned short wfa_defined_debug;

/* globally define the function table */
const xcCommandFuncPtr gWfaCmdFuncTbl[WFA_STA_COMMANDS_END+1] =
{
    /*
    ###################################################################################################
    #                                 GENERIC FUNCTIONS                                               #
    ###################################################################################################
    */
    /* Traffic Agent Commands */
    [WFA_GET_VERSION_TLV] = agtCmdProcGetVersion,
    [WFA_TRAFFIC_SEND_PING_TLV] = wfaTGSendPing,            /*    WFA_TRAFFIC_SEND_PING_TLV          (2) */
    [WFA_TRAFFIC_STOP_PING_TLV] = wfaTGStopPing,            /*    WFA_TRAFFIC_STOP_PING_TLV          (3) */
    [WFA_TRAFFIC_AGENT_CONFIG_TLV] = wfaTGConfig,              /*    WFA_TRAFFIC_AGENT_CONFIG_TLV       (4) */
    [WFA_TRAFFIC_AGENT_SEND_TLV] = wfaTGSendStart,           /*    WFA_TRAFFIC_AGENT_SEND_TLV         (5) */
    [WFA_TRAFFIC_AGENT_RECV_START_TLV] = wfaTGRecvStart,           /*    WFA_TRAFFIC_AGENT_RECV_START_TLV   (6) */
    [WFA_TRAFFIC_AGENT_RECV_STOP_TLV] = wfaTGRecvStop,            /*    WFA_TRAFFIC_AGENT_RECV_STOP_TLV    (7) */
    [WFA_TRAFFIC_AGENT_RESET_TLV] = wfaTGReset,               /*    WFA_TRAFFIC_AGENT_RESET_TLV        (8) */

    /*
    ###################################################################################################
    #                                   STAUT FUNCTIONS                                               #
    ###################################################################################################
    */
    /* Control and Configuration Commands */ 
    [WFA_STA_GET_IP_CONFIG_TLV] = wfaStaGetIpConfig,        /*    WFA_STA_GET_IP_CONFIG_TLV          (10)*/
    [WFA_STA_SET_IP_CONFIG_TLV] = wfaStaSetIpConfig,        /*    WFA_STA_SET_IP_CONFIG_TLV          (11)*/
    [WFA_STA_GET_MAC_ADDRESS_TLV] = wfaStaGetMacAddress,      /*    WFA_STA_GET_MAC_ADDRESS_TLV        (12)*/
    [WFA_STA_SET_MAC_ADDRESS_TLV] = wfaStaSetMacAddr,         /*    WFA_STA_SET_MAC_ADDRESS_TLV        (13)*/
    [WFA_STA_IS_CONNECTED_TLV] = wfaStaIsConnected,        /*    WFA_STA_IS_CONNECTED_TLV           (14)*/
    [WFA_STA_VERIFY_IP_CONNECTION_TLV] = wfaStaVerifyIpConnection, /*    WFA_STA_VERIFY_IP_CONNECTION_TLV   (15)*/
    [WFA_STA_GET_BSSID_TLV] = wfaStaGetBSSID,           /*    WFA_STA_GET_BSSID_TLV              (16)*/
    [WFA_STA_GET_STATS_TLV] = wfaStaGetStats,           /*    WFA_STA_GET_STATS_TLV              (17)*/
    [WFA_STA_SET_ENCRYPTION_TLV] = wfaSetEncryption,         /*    WFA_STA_SET_ENCRYPTION_TLV         (18)*/
    [WFA_STA_SET_PSK_TLV] = wfaStaSetPSK,             /*    WFA_STA_SET_PSK_TLV                (19)*/
    [WFA_STA_SET_EAPTLS_TLV] = wfaStaSetEapTLS,          /*    WFA_STA_SET_EAPTLS_TLV             (20)*/
    [WFA_STA_SET_UAPSD_TLV] = wfaStaSetUAPSD,           /*    WFA_STA_SET_UAPSD_TLV              (21)*/
    [WFA_STA_ASSOCIATE_TLV] = wfaStaAssociate,          /*    WFA_STA_ASSOCIATE_TLV              (22)*/
    [WFA_STA_SET_EAPTTLS_TLV] = wfaStaSetEapTTLS,         /*    WFA_STA_SET_EAPTTLS_TLV            (23)*/
    [WFA_STA_SET_EAPSIM_TLV] = wfaStaSetEapSIM,          /*    WFA_STA_SET_EAPSIM_TLV             (24)*/
    [WFA_STA_SET_PEAP_TLV] = wfaStaSetPEAP,            /*    WFA_STA_SET_PEAP_TLV               (25)*/
    [WFA_STA_SET_IBSS_TLV] = wfaStaSetIBSS,            /*    WFA_STA_SET_IBSS_TLV               (26)*/
    [WFA_STA_GET_INFO_TLV] = wfaStaGetInfo,            /*    WFA_STA_GET_INFO_TLV               (27)*/
    [WFA_DEVICE_GET_INFO_TLV] = wfaDeviceGetInfo,         /*    WFA_DEVICE_GET_INFO_TLV            (28)*/
    [WFA_DEVICE_LIST_IF_TLV] = wfaDeviceListIF,          /*    WFA_DEVICE_LIST_IF_TLV]            (29)*/
    [WFA_STA_DEBUG_SET_TLV] = wfaStaDebugSet,           /*    WFA_STA_DEBUG_SET                  (30)*/
    [WFA_STA_SET_MODE_TLV] = wfaStaSetMode,            /*    WFA_STA_SET_MODE                   (31)*/
    [WFA_STA_UPLOAD_TLV] = wfaStaUpload,             /*    WFA_STA_UPLOAD                     (32)*/
    [WFA_STA_SET_WMM_TLV] = wfaStaSetWMM,             /*    WFA_STA_SETWMM                     (33)*/
    [WFA_STA_REASSOCIATE_TLV] = wfaStaReAssociate,        /*    WFA_STA_REASSOCIATE                (34)*/
    [WFA_STA_SET_PWRSAVE_TLV] = wfaStaSetPwrSave,         /*    WFA_STA_SET_PWRSAVE                (35)*/
    [WFA_STA_SEND_NEIGREQ_TLV] = wfaStaTestBedCmd,         /*    WFA_STA_SEND_NEIGREQ               (36)*/
    [WFA_STA_PRESET_PARAMETERS_TLV] = wfaStaPresetParams,       /*    WFA_STA_PRESET_PARAMETERS          (37)*/
    [WFA_STA_SET_EAPFAST_TLV] = wfaStaSetEapFAST,         /*    WFA_STA_SET_EAPFAST_TLV            (38)*/
    [WFA_STA_SET_EAPAKA_TLV] = wfaStaSetEapAKA,       /*    WFA_STA_SET_EAPAKA_TLV             (49)*/
    [WFA_STA_SET_EAPAKAPRIME_TLV] = wfaStaSetEapAKAPRIME,         /*    WFA_STA_SET_EAPAKA_TLV             (49)*/
    [WFA_STA_SET_SYSTIME_TLV] = wfaStaSetSystime,         /*    WFA_STA_SET_SYSTIME_TLV            (40)*/
    [WFA_STA_SET_11N_TLV] = wfaStaSet11n,             /*    WFA_STA_SET_11n_TLV                (41)*/
    [WFA_STA_SET_WIRELESS_TLV] = wfaStaSetWireless,       /*    WFA_STA_SET_WIRELESS_TLV           (42)*/
    [WFA_STA_SEND_ADDBA_TLV] = wfaStaTestBedCmd,          /*    WFA_STA_SEND_ADDBA_TLV             (43)*/
    [WFA_STA_SEND_COEXIST_MGMT_TLV] = wfaStaTestBedCmd,         /*    WFA_STA_SET_COEXIST_MGMT_TLV       (44)*/
    [WFA_STA_SET_RIFS_TEST_TLV] = wfaStaTestBedCmd,         /*    WFA_STA_SET_RIFS_TEST_TLV          (45)*/
    [WFA_STA_RESET_DEFAULT_TLV] = wfaStaResetDefault,       /*    WFA_STA_RESET_DEFAULT_TLV          (46)*/
    [WFA_STA_DISCONNECT_TLV] = wfaStaDisconnect,         /*    WFA_STA_DISCONNECT_TLV             (47)*/
    [WFA_STA_DEV_SEND_FRAME_TLV] = wfaStaDevSendFrame,       /*    WFA_STA_DEV_SEND_FRAME_TLV         (48)*/
    [WFA_STA_SET_SECURITY_TLV] = wfaStaSetSecurity,        /*    WFA_STA_SET_SECURITY_TLV           (49)*/
    [WFA_STA_SET_RADIO_TLV] = wfaStaSetRadio,           /*    WFA_STA_SET_RADIO_TLV              (50)*/
    [WFA_STA_SET_RFEATURE_TLV] = wfaStaSetRFeature,        /*    WFA_STA_RFEATURE_TLV               (51)*/
    [WFA_STA_SENDTCP_TLV] = wfaStaSendTCP,
    [WFA_STA_RCVTCP_TLV] = wfaStaRcvTCP,
    [WFA_STA_READ_TCP_TLV] = wfaStaReadTCP,
    [WFA_STA_STOP_IPERF_TLV] = wfaStaStopIperf,
    [WFA_STA_SCAN_TLV] = wfaStaScan,
    [WFA_STA_SET_POWER_SAVE_TLV] = wfaStaSetPowerSave,

    /*
    ###################################################################################################
    #                                     P2P FUNCTIONS                                               #
    ###################################################################################################
    */
    [WFA_STA_P2P_GET_DEV_ADDRESS_TLV] = wfaStaGetP2pDevAddress,     /*    WFA_STA_GET_P2P_DEV_ADDRESS_TLV        (50)*/
    [WFA_STA_P2P_SETP2P_TLV] = wfaStaSetP2p,                /*    WFA_STA_SET_P2P_TLV                    (51)*/
    [WFA_STA_P2P_CONNECT_TLV] = wfaStaP2pConnect,           /*    WFA_STA_P2P_CONNECT_TLV                (52)*/
    [WFA_STA_P2P_START_AUTO_GO_TLV] = wfaStaStartAutoGo,            /*    WFA_STA_START_AUTO_GO                  (53)*/
    [WFA_STA_P2P_START_GRP_FORMATION_TLV] = wfaStaP2pStartGrpFormation, /*    WFA_STA_P2P_START_GRP_FORMATION_TLV    (54)*/
    [WFA_STA_P2P_DISSOLVE_TLV] = wfaStaP2pDissolve,          /*    WFA_STA_P2P_DISSOLVE_TLV               (55)*/
    [WFA_STA_P2P_SEND_INV_REQ_TLV] = wfaStaSendP2pInvReq,        /*    WFA_STA_SEND_P2P_INV_REQ_TLV           (56)*/
    [WFA_STA_P2P_ACCEPT_INV_REQ_TLV] = wfaStaAcceptP2pInvReq,       /*    WFA_STA_ACCEPT_P2P_INV_REQ_TLV         (57)*/
    [WFA_STA_P2P_SEND_PROV_DIS_REQ_TLV] = wfaStaSendP2pProvDisReq,    /*    WFA_STA_SEND_P2P_PROV_DIS_REQ_TLV      (58)*/
    [WFA_STA_WPS_SETWPS_PBC_TLV] = wfaStaSetWpsPbc,            /*    WFA_STA_SET_WPS_PBC_TLV                (59)*/
    [WFA_STA_WPS_READ_PIN_TLV] = wfaStaWpsReadPin,               /*    WFA_STA_WPS_READ_PIN_TLV                 (60)*/
    [WFA_STA_WPS_ENTER_PIN_TLV] = wfaStaWpsEnterPin,              /*    WFA_STA_WPS_ENTER_PIN_TLV                  (61)*/
    [WFA_STA_P2P_GET_PSK_TLV] = wfaStaGetPsk,                   /*    WFA_STA_GET_PSK_TLV                      (62)*/
    [WFA_STA_P2P_RESET_TLV] = wfaStaP2pReset,                 /*    WFA_STA_P2P_RESET_TLV                    (63)*/
    [WFA_STA_WPS_READ_LABEL_TLV] = wfaStaWpsReadLabel,             /*    WFA_STA_WPS_READ_LABEL_TLV               (64)*/
    [WFA_STA_P2P_GET_IP_CONFIG_TLV] = wfaStaGetP2pIpConfig,           /*    WFA_STA_GET_P2P_IP_CONFIG_TLV            (65)*/
    [WFA_STA_P2P_SEND_SERVICE_DISCOVERY_REQ_TLV] = wfaStaSendServiceDiscoveryReq,  /*    WFA_STA_SEND_SERVICE_DISCOVERY_REQ_TLV   (66)*/
    [WFA_STA_P2P_SEND_PRESENCE_REQ_TLV] = wfaStaSendP2pPresenceReq,       /*    WFA_STA_SEND_P2P_PRESENCE_REQ_TLV        (67)*/
    [WFA_STA_P2P_SET_SLEEP_TLV] = wfaStaSetSleepReq,              /*    WFA_STA_SEND_P2P_PRESENCE_REQ_TLV        (68)*/
    [WFA_STA_P2P_SET_OPPORTUNISTIC_PS_TLV] = wfaStaSetOpportunisticPsReq,    /*    WFA_STA_SET_OPPORTUNISTIC_PS_TLV         (69)*/
    [WFA_STA_P2P_ADD_ARP_TABLE_ENTRY_TLV] = wfaStaAddArpTableEntry,         /*    WFA_STA_ADD_ARP_TABLE_ENTRY_TLV          (70)*/
    [WFA_STA_P2P_BLOCK_ICMP_RESPONSE_TLV] = wfaStaBlockICMPResponse,        /*    WFA_STA_BLOCK_ICMP_RESPONSE_TLV          (71)*/

    /*
    ###################################################################################################
    #                                     WFD FUNCTIONS                                               #
    ###################################################################################################
    */
    [WFA_STA_START_WFD_CONNECTION_TLV] = wfaStaStartWfdConnection,   /*   WFA_STA_START_WFD_CONNECTION_TLV    (74)*/
    [WFA_STA_CONNECT_GO_START_WFD_TLV] = wfaStaConnectGoStartWfd,    /*   WFA_STA_CONNECT_GO_START_WFD_TLV    (76)*/
    [WFA_STA_GENERATE_EVENT_TLV] = wfaStaGenerateEvent,        /*   WFA_STA_GENERATE_EVENT_TLV          (77)*/
    [WFA_STA_REINVOKE_WFD_SESSION_TLV] = wfaStaReinvokeWfdSession,   /*   WFA_STA_REINVOKE_WFD_SESSION_TLV    (78)*/
    [WFA_STA_GET_PARAMETER_TLV] = wfaStaGetParameter,         /*   WFA_STA_GET_PARAMETER_TLV           (79)*/


    /*
    ###################################################################################################
    #                                   APUT FUNCTIONS                                                #
    ###################################################################################################
    */
    [WFA_AP_SET_WIRELESS_TLV] = wfaApSetWireless,     /*WFA_AP_SET_WIRELESS_TLV ()*/
    [WFA_AP_SET_SECURITY_TLV] = wfaAPSetSecurity,     /*WFA_AP_SET_SECURITY()*/
    [WFA_AP_SET_APQOS_TLV] = wfaAPSetApQos,        /*WFA_AP_SET_APQOS_TLV()*/
    [WFA_AP_SET_STAQOS_TLV] = wfaAPSetStaQos,       /*WFA_AP_SET_STAQOS()*/
    [WFA_AP_SET_11N_WIRELESS_TLV] = wfaAPSet11nWireless,  /*WFA_AP_SET_11N_WIRELESS_TLV()*/
    [WFA_AP_GET_WIRELESS_TLV] = wfaAPGetWireless,     /*WFA_AP_GET_WIRELESS_TLV()*/
    [WFA_AP_GET_APQOS_TLV] = wfaAPGetApQos,        /*WFA_AP_GET_APQOS_TLV()*/
    [WFA_AP_SET_RADIUS_TLV] = wfaAPSetRadius,       /*WFA_AP_SET_RADIUS()*/
    [WFA_AP_CA_VERSION_TLV] = wfaAPCaVersion,       /*WFA_AP_CA_VERSION_TLV()*/
    [WFA_AP_RESET_DEFAULT_TLV] = wfaAPResetDefault,    /*WFA_AP_RESET_DEFAULT_TLV()*/
    [WFA_AP_REBOOT_TLV] = wfaAPReboot,          /*WFA_AP_REBOOT_TLV()*/
    [WFA_AP_CONFIG_COMMIT_TLV] = wfaAPConfigCommit,    /*WFA_AP_CONFIG_COMMIT_TLV()*/
    [WFA_AP_GET_INFO_TLV] = wfaAPGetInfo,         /*WFA_AP_GET_INFO_TLV()*/
    [WFA_AP_DEAUTH_STA_TLV] = wfaAPDeAuthSta,       /*WFA_AP_DEAUTH_STA_TLV()*/
    [WFA_AP_ADD_NEWIF_TLV] = wfaAPAddNewIF,        /*WFA_AP_ADD_IF_TLV()*/
    [WFA_AP_SET_PMF_TLV] = wfaAPSetPMF,          /*WFA_AP_SET_PMF_TLV()*/
    [WFA_AP_GET_MAC_ADDRESS_TLV] = wfaAPGetMacAddress,   /*WFA_AP_GET_MAC_ADDRESS_TLV()*/
    [WFA_AP_SET_11D_TLV] = wfaAPSet11d,           /*WFA_AP_SET_11D_TLV()*/
    [WFA_AP_SET_11H_TLV] = wfaAPSet11h,            /*WFA_AP_SET_11H_TLV()*/
    [WFA_AP_SET_RFEATURE_TLV] = wfaAPSetRFeature            /*WFA_AP_SET_RFEATURE_TLV()*/
};


/*
 * NotDefinedYet(): a dummy function
 */
int NotDefinedYet(int len, unsigned char *params, int *respLen, BYTE *respBuf)
{
    DPRINT_WARNING("The command processing function not defined.\r\n");


    /* need to send back a response */

    return WFA_SUCCESS;
}
