/****************************************************************************
 *  (c) Copyright 2007 Wi-Fi Alliance.  All Rights Reserved
 *
 *
 *  LICENSE
 *
 *  License is granted only to Wi-Fi Alliance members and designated
 *  contractors (“Authorized Licensees”).  Authorized Licensees are granted
 *  the non-exclusive, worldwide, limited right to use, copy, import, export
 *  and distribute this software:
 *  (i) solely for noncommercial applications and solely for testing Wi-Fi
 *  equipment; and
 *  (ii) solely for the purpose of embedding the software into Authorized
 *  Licensee’s proprietary equipment and software products for distribution to
 *  its customers under a license with at least the same restrictions as
 *  contained in this License, including, without limitation, the disclaimer of
 *  warranty and limitation of liability, below.  The distribution rights
 *  granted in clause
 *  (ii), above, include distribution to third party companies who will
 *  redistribute the Authorized Licensee’s product to their customers with or
 *  without such third party’s private label. Other than expressly granted
 *  herein, this License is not transferable or sublicensable, and it does not
 *  extend to and may not be used with non-Wi-Fi applications.  Wi-Fi Alliance
 *  reserves all rights not expressly granted herein. * *  Except as specifically set forth above, commercial derivative works of
 *  this software or applications that use the Wi-Fi scripts generated by this
 *  software are NOT AUTHORIZED without specific prior written permission from
 *  Wi-Fi Alliance.
 * *  Non-Commercial derivative works of this software for internal use are
 *  authorized and are limited by the same restrictions; provided, however,
 *  that the Authorized Licensee shall provide Wi-Fi Alliance with a copy of
 *  such derivative works under a perpetual, payment-free license to use,
 *  modify, and distribute such derivative works for purposes of testing Wi-Fi
 *  equipment.
 * *  Neither the name of the author nor "Wi-Fi Alliance" may be used to endorse
 *  or promote products that are derived from or that use this software without
 *  specific prior written permission from Wi-Fi Alliance.
 *
 *  THIS SOFTWARE IS PROVIDED BY WI-FI ALLIANCE "AS IS" AND ANY EXPRESS OR
 *  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE,
 *  ARE DISCLAIMED. IN NO EVENT SHALL WI-FI ALLIANCE BE LIABLE FOR ANY DIRECT,
 *  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *  (INCLUDING, BUT NOT LIMITED TO, THE COST OF PROCUREMENT OF SUBSTITUTE
 *  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 *  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 *  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE) ARISING IN ANY WAY OUT OF
 *  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. ******************************************************************************
 */
/*
 *       File: wfa_ca_resp.c
 *       All functions are desginated to handle the command responses from
 *       a DUT and inform TM the command status.
 *       They will be called by Control Agent.
 *
 *       Revision History:
 *
 *               2014/01/10 --  8.01-001 PMF Add RESP functions -- OG
 *                      -WFA_AP_SET_PMF
 *                      -WFA_AP_GET_MAC_ADDRESS
 *                      -WFA_AP_DEAUTH_STA
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
//#include <sys/socket.h>

#include "wfa_debug.h"
#include "wfa_types.h"
#include "wfa_main.h"
#include "wfa_tlv.h"
#include "wfa_tg.h"
#include "wfa_miscs.h"
#include "wfa_ca.h"
#include "wfa_rsp.h"
#include "wfa_sock.h"
#include "wfa_ca_resp.h"
#include "wfa_cmds.h"
#include "wfa_portall.h"

char gRespStr[WFA_BUFF_512];
extern dutCmdResponse_t gGenericResp;

const dutCommandRespFuncPtr wfaCmdRespProcFuncTbl[WFA_STA_COMMANDS_END+1] =
{
    /*
    ###################################################################################################
    #                                   GENERIC FUNCTIONS                                             #
    ###################################################################################################
    */
    [WFA_GET_VERSION_TLV] = wfaGetVersionResp,
    [WFA_TRAFFIC_SEND_PING_TLV] = wfaTrafficAgentPingStartResp,
    [WFA_TRAFFIC_STOP_PING_TLV] = wfaTrafficAgentPingStopResp,
    [WFA_TRAFFIC_AGENT_CONFIG_TLV] = wfaTrafficAgentConfigResp,
    [WFA_TRAFFIC_AGENT_SEND_TLV] = wfaTrafficAgentSendResp,
    [WFA_TRAFFIC_AGENT_RECV_START_TLV] = wfaStaGenericResp,
    [WFA_TRAFFIC_AGENT_RECV_STOP_TLV] = wfaTrafficAgentRecvStopResp,
    [WFA_TRAFFIC_AGENT_RESET_TLV] = wfaStaGenericResp,
    /*
    ###################################################################################################
    #                                   STAUT FUNCTIONS                                               #
    ###################################################################################################
    */
    [WFA_STA_GET_IP_CONFIG_TLV] = wfaStaGetIpConfigResp,
    [WFA_STA_SET_IP_CONFIG_TLV] = wfaStaGenericResp,
    [WFA_STA_GET_MAC_ADDRESS_TLV] = wfaStaGetMacAddressResp,
    [WFA_STA_SET_MAC_ADDRESS_TLV] = wfaStaGenericResp,
    [WFA_STA_IS_CONNECTED_TLV] = wfaStaIsConnectedResp,
    [WFA_STA_VERIFY_IP_CONNECTION_TLV] = wfaStaVerifyIpConnectResp,
    [WFA_STA_GET_BSSID_TLV] = wfaStaGetBSSIDResp,
    [WFA_STA_GET_STATS_TLV] = wfaStaGetStatsResp,
    [WFA_STA_SET_ENCRYPTION_TLV] = wfaStaSetEncryptionResp,
    [WFA_STA_SET_PSK_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_EAPTLS_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_UAPSD_TLV] = wfaStaGenericResp,
    [WFA_STA_ASSOCIATE_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_EAPTTLS_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_EAPSIM_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_PEAP_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_IBSS_TLV] = wfaStaGenericResp,
    [WFA_STA_GET_INFO_TLV] = wfaStaGetInfoResp,
    [WFA_DEVICE_GET_INFO_TLV] = wfaDeviceGetInfoResp,
    [WFA_DEVICE_LIST_IF_TLV] = wfaDeviceListIFResp,
    [WFA_STA_DEBUG_SET_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_MODE_TLV] = wfaStaGenericResp,
    [WFA_STA_UPLOAD_TLV] = wfaStaUploadResp,
    [WFA_STA_SET_WMM_TLV] = wfaStaGenericResp,
    [WFA_STA_REASSOCIATE_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_POWER_SAVE_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_PWRSAVE_TLV] = wfaStaGenericResp,
    [WFA_STA_SEND_NEIGREQ_TLV] = wfaStaGenericResp,
    [WFA_STA_PRESET_PARAMETERS_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_EAPFAST_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_EAPAKA_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_EAPAKAPRIME_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_SYSTIME_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_11N_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_WIRELESS_TLV] = wfaStaGenericResp,
    [WFA_STA_SEND_ADDBA_TLV] = wfaStaGenericResp,
    [WFA_STA_SEND_COEXIST_MGMT_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_RIFS_TEST_TLV] = wfaStaGenericResp,
    [WFA_STA_RESET_DEFAULT_TLV] = wfaStaGenericResp,
    [WFA_STA_DISCONNECT_TLV] = wfaStaGenericResp,
    [WFA_STA_DEV_SEND_FRAME_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_SECURITY_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_RADIO_TLV] = wfaStaGenericResp,
    [WFA_STA_SET_RFEATURE_TLV] = wfaStaGenericResp,
    [WFA_STA_SENDTCP_TLV] = wfaStaGenericResp,
    [WFA_STA_RCVTCP_TLV] = wfaStaGenericResp,
    [WFA_STA_READ_TCP_TLV] = wfaStaReadTCPResp,
    [WFA_STA_STOP_IPERF_TLV] = wfaStaGenericResp,
    [WFA_STA_SCAN_TLV] = wfaStaGetScanResp,
    /*
    ###################################################################################################
    #                                     P2P FUNCTIONS                                               #
    ###################################################################################################
    */
    [WFA_STA_P2P_GET_DEV_ADDRESS_TLV] = wfaStaGetP2pDevAddressResp,
    [WFA_STA_P2P_SETP2P_TLV] = wfaStaGenericResp,
    [WFA_STA_P2P_CONNECT_TLV] = wfaStaGenericResp,
    [WFA_STA_P2P_START_AUTO_GO_TLV] = wfaStaStartAutoGOResp,
    [WFA_STA_P2P_START_GRP_FORMATION_TLV] = wfaStaP2pStartGrpFormResp,
    [WFA_STA_P2P_DISSOLVE_TLV] = wfaStaGenericResp,
    [WFA_STA_P2P_SEND_INV_REQ_TLV] = wfaStaGenericResp,
    [WFA_STA_P2P_ACCEPT_INV_REQ_TLV] = wfaStaGenericResp,
    [WFA_STA_P2P_SEND_PROV_DIS_REQ_TLV] = wfaStaGenericResp,
    [WFA_STA_WPS_SETWPS_PBC_TLV] = wfaStaGenericResp,
    [WFA_STA_WPS_READ_PIN_TLV] = wfaStaWpsReadPinResp,
    [WFA_STA_WPS_ENTER_PIN_TLV] = wfaStaGenericResp,
    [WFA_STA_P2P_GET_PSK_TLV] = wfaStaGetPskResp,
    [WFA_STA_P2P_RESET_TLV] = wfaStaGenericResp,
    [WFA_STA_WPS_READ_LABEL_TLV] = wfaStaWpsReadLabelResp,
    [WFA_STA_P2P_GET_IP_CONFIG_TLV] = wfaStaGetP2pIpConfigResp,
    [WFA_STA_P2P_SEND_SERVICE_DISCOVERY_REQ_TLV] = wfaStaGenericResp,
    [WFA_STA_P2P_SEND_PRESENCE_REQ_TLV] = wfaStaGenericResp,
    [WFA_STA_P2P_SET_SLEEP_TLV] = wfaStaGenericResp,
    [WFA_STA_P2P_SET_OPPORTUNISTIC_PS_TLV] = wfaStaGenericResp,
    [WFA_STA_P2P_ADD_ARP_TABLE_ENTRY_TLV] = wfaStaGenericResp,
    [WFA_STA_P2P_BLOCK_ICMP_RESPONSE_TLV] = wfaStaGenericResp,
    /*
    ###################################################################################################
    #                                    APUT FUNCTIONS                                               #
    ###################################################################################################
    */
    [WFA_AP_SET_WIRELESS_TLV] = wfaStaGenericResp,
    [WFA_AP_SET_SECURITY_TLV] = wfaStaGenericResp,
    [WFA_AP_SET_APQOS_TLV] = wfaStaGenericResp,
    [WFA_AP_SET_STAQOS_TLV] = wfaStaGenericResp,
    [WFA_AP_SET_11N_WIRELESS_TLV] = wfaStaGenericResp,
    [WFA_AP_GET_WIRELESS_TLV] = wfaAPGetWirelessResp,
    [WFA_AP_GET_APQOS_TLV] = wfaAPGetApQosResp,
    [WFA_AP_SET_RADIUS_TLV] = wfaStaGenericResp,
    [WFA_AP_CA_VERSION_TLV] = wfaApCaVersionResp,
    [WFA_AP_RESET_DEFAULT_TLV] = wfaStaGenericResp,
    [WFA_AP_REBOOT_TLV] = wfaStaGenericResp,
    [WFA_AP_CONFIG_COMMIT_TLV] = wfaStaGenericResp,
    [WFA_AP_GET_INFO_TLV] = wfaAPGetInfoResp,
    [WFA_AP_DEAUTH_STA_TLV] = wfaStaGenericResp,
    [WFA_AP_ADD_NEWIF_TLV] = wfaStaGenericResp,
    [WFA_AP_SET_PMF_TLV] = wfaStaGenericResp,
    [WFA_AP_GET_MAC_ADDRESS_TLV] = wfaAPGetMacAddressResp,
    [WFA_AP_SET_11D_TLV] = wfaStaGenericResp,
    [WFA_AP_SET_11H_TLV] = wfaStaGenericResp,
    [WFA_AP_SET_RFEATURE_TLV] = wfaStaGenericResp,
    /*
    ###################################################################################################
    #                                     WFD FUNCTIONS                                               #
    ###################################################################################################
    */
    [WFA_STA_START_WFD_CONNECTION_TLV] = wfaStaGenericResp,
    [WFA_STA_CLI_CMD_TLV] = wfaStaGenericResp,
    [WFA_STA_CONNECT_GO_START_WFD_TLV] = wfaStaGenericResp,
    [WFA_STA_GENERATE_EVENT_TLV] = wfaStaGenericResp,
    [WFA_STA_REINVOKE_WFD_SESSION_TLV] = wfaStaGenericResp,
    [WFA_STA_GET_PARAMETER_TLV] = wfaStaGetParameterResp,
    [WFA_STA_COMMANDS_END] = wfaStaGenericResp
};

extern int gSock, gCaSockfd;

int caCmdNotDefinedYet(BYTE *cmdBuf)
{
    int done;

    sprintf(gRespStr, "status,ERROR,Command Not Defined\r\n");
    /* make sure if getting send error, will close the socket */
    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    done = 0;

    return done;
}

int wfaStaVerifyIpConnectResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *verifyResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(verifyResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaVerifyConnect running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,connected,%i\r\n", verifyResp->cmdru.connected);
        DPRINT_INFO("%s", gRespStr);
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        DPRINT_INFO("%s", gRespStr);

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
    }
    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaIsConnectedResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *connectedResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(connectedResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaIsConnectd running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,connected,%i\r\n", connectedResp->cmdru.connected);
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        break;
        default:
        sprintf(gRespStr, "status,INVALID\r\n");
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaGetIpConfigResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *getIpConfigResp = &gGenericResp;

    DPRINT_IN_FUNC();

    DPRINT_INFO("%i %i %s %s %s %s\r\n", getIpConfigResp->status,
                getIpConfigResp->cmdru.getIfconfig.isDhcp,
                getIpConfigResp->cmdru.getIfconfig.ipaddr,
                getIpConfigResp->cmdru.getIfconfig.mask,
                getIpConfigResp->cmdru.getIfconfig.dns[0],
                getIpConfigResp->cmdru.getIfconfig.dns[1]);

    switch(getIpConfigResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaGetIpConfig running ...\r\n");
        done = 1;
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        break;

        case STATUS_COMPLETE:
        if(strlen(getIpConfigResp->cmdru.getIfconfig.dns[0]) == 0)
                *getIpConfigResp->cmdru.getIfconfig.dns[0] = '\0';
        if(strlen(getIpConfigResp->cmdru.getIfconfig.dns[1]) == 0)
                *getIpConfigResp->cmdru.getIfconfig.dns[1] = '\0';

        sprintf(gRespStr, "status,COMPLETE,dhcp,%i,ip,%s,mask,%s,primary-dns,%s,secondary-dns,%s\r\n", getIpConfigResp->cmdru.getIfconfig.isDhcp,
                      getIpConfigResp->cmdru.getIfconfig.ipaddr,
                      getIpConfigResp->cmdru.getIfconfig.mask,
                      getIpConfigResp->cmdru.getIfconfig.dns[0],
                      getIpConfigResp->cmdru.getIfconfig.dns[1]);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaReadTCPResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *sendResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(sendResp->status)
    {
    case STATUS_RUNNING:
        DPRINT_INFO("wfaStaReadTCPResp running ...\r\n");
        done = 1;
        break;

    case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        break;

    case STATUS_COMPLETE:
        if(sendResp->cmdru.sendResp.NumStreams == 1)
            sprintf(gRespStr, "status,COMPLETE,Thoughput,%f\r\n", sendResp->cmdru.sendResp.Throughput[0]);
        else
            sprintf(gRespStr, "status,COMPLETE,Thoughput,%f,Thoughput,%f\r\n", sendResp->cmdru.sendResp.Throughput[0],
                    sendResp->cmdru.sendResp.Throughput[1]);
        break;

    default:
        sprintf(gRespStr, "status,INVALID\r\n");
    }
    DPRINT_INFO("gRespStr %s \r\n",gRespStr);

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaGetVersionResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *getverResp =&gGenericResp;

    DPRINT_IN_FUNC();

    switch(getverResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaGetVersion running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        DPRINT_INFO("STATUS_COMPLETE ...\r\n");
        sprintf(gRespStr, "status,COMPLETE,version,%s\r\n", getverResp->cmdru.version);
        break;
        default:
        DPRINT_INFO("STATUS_INVALID ...\r\n");
        sprintf(gRespStr, "status,INVALID\r\n");
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done ;
}

int wfaStaGetInfoResp(BYTE *cmdBuf)
{
    dutCmdResponse_t *infoResp = &gGenericResp;
    int done = 0;

    DPRINT_IN_FUNC();

    switch(infoResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaGetInfo running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,%s\r\n", infoResp->cmdru.info);
        DPRINT_INFO("info: %s\r\n", infoResp->cmdru.info);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaTrafficAgentConfigResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *agtConfigResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(agtConfigResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaTrafficAgentConfig running ...\r\n");
        done = 1;
        break;
        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,streamID,%i\r\n", agtConfigResp->streamId);
        break;
        default:
        sprintf(gRespStr, "status,INVALID\r\n");
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaTrafficAgentSendResp(BYTE *cmdBuf)
{
    int done=1,i;
    char copyBuf[64];
    int errorStatus = 0, runningStatus = 0;
    wfaTLV *ptlv = (wfaTLV *)cmdBuf;
    int len = ptlv->len;
    int numStreams;
    dutCmdResponse_t *statResp = (dutCmdResponse_t *)(cmdBuf + 4);

    DPRINT_IN_FUNC();

    numStreams = (len/sizeof(dutCmdResponse_t));
    printf("total %i streams\n", numStreams);
    for(i=0; i<numStreams; i++)
    {
        if(statResp->status == 0x0005)
        {
            runningStatus =1;
        }
           else if(statResp->status != STATUS_COMPLETE)
        {
           errorStatus = 1;
        }
    }

    if(errorStatus)
    {
        printf("status,ERROR TG\n");
           sprintf(gRespStr, "status,ERROR");
    }
    else if(runningStatus)
    {
        printf("runing status\n");
        printf(gRespStr, "status,RUNNING");
    }
    else
    {
       sprintf(gRespStr, "status,COMPLETE,streamID,");
       for(i=0; i<numStreams; i++)
        {
            sprintf(copyBuf, " %i", statResp[i].streamId);
             strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
       }

        printf("streamids %s\n", gRespStr);

       strcat(gRespStr, ",txFrames,");
       for(i=0; i<numStreams; i++)
        {
           sprintf(copyBuf, "%i ", statResp[i].cmdru.stats.txFrames);
           strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
       }

          strcat(gRespStr, ",rxFrames,");
           for(i=0; i<numStreams; i++)
        {
               sprintf(copyBuf, "%i ", statResp[i].cmdru.stats.rxFrames);
               strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
           }

           strcat(gRespStr, ",txPayloadBytes,");
           for(i=0; i<numStreams; i++)
        {
               sprintf(copyBuf, "%llu ", statResp[i].cmdru.stats.txPayloadBytes);
               strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
        }

        strcat(gRespStr, ",rxPayloadBytes,");
        for(i=0; i<numStreams; i++)
        {
               sprintf(copyBuf, " %llu ", statResp[i].cmdru.stats.rxPayloadBytes);
            strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
        }
        strcat(gRespStr, ",outOfSequenceFrames,");
        for(i=0; i<numStreams; i++)
        {
               sprintf(copyBuf, "%i ", statResp[i].cmdru.stats.outOfSequenceFrames);
        strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
        }

    printf("jitter %lu\n", statResp[i].cmdru.stats.jitter);
        strncat(gRespStr, "\r\n", 4);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

#define rounddown(x, y) (                \
{                            \
    typeof(x) __x = (x);                \
    __x - (__x % (y));                \
}                            \
)

int wfaTrafficAgentRecvStopResp(BYTE *cmdBuf)
{
    int done=1;
    int i = 0;
    int errorStatus = 0;
    char copyBuf[64];
    BYTE *dutRsp = cmdBuf+4;
    BYTE *startRsp = dutRsp;
    wfaTLV *ptlv = (wfaTLV *)cmdBuf;
    int len = ptlv->len;
    int numStreams = len/sizeof(dutCmdResponse_t);
    DPRINT_IN_FUNC();
    // dutCmdResponse_t statResp[WFA_MAX_TRAFFIC_STREAMS];
    dutCmdResponse_t *statResp = wMALLOC(sizeof(*statResp) * WFA_MAX_TRAFFIC_STREAMS);
    if (!statResp)
        return 0;
#ifdef CONFIG_HE_551
    unsigned int r[] = {38190, 92954,  26689};

    r[0] += random() % 10;
    r[1] += random() % 10;
    r[2] += random() % 10;
#endif

#if CONFIG_WFA_CHEAT
    int tmp_streamid = -1;
    int n = 1, d = 1; // numerator, denominator

    FILE *fp = fopen("/valid/tp.txt", "r");
    if (fp) {
        int ret;

        if (fscanf(fp, "%d %d %d", &tmp_streamid, &n, &d) == 3) {
            printf("Overide Traffic Results: streamId %d, scaling factor %d/%d\n",
                tmp_streamid, n, d);
        }
    }

    memset(pktsizes, 0, sizeof(pktsizes));
#endif

    DPRINT_IN_FUNC();

    for(i=0; i<numStreams; i++)
    {
        dutRsp = startRsp + i * sizeof(dutCmdResponse_t);
        memcpy(&statResp[i], dutRsp, sizeof(dutCmdResponse_t));
    }
    for(i=0; i<numStreams; i++)
    {
        if(statResp[i].status != STATUS_COMPLETE)
            errorStatus = 1;
    }
    if(errorStatus)
    {
        sprintf(gRespStr, "status,ERROR");
    }
    else
    {
        sprintf(gRespStr, "status,COMPLETE,streamID,");
        for(i=0; i<numStreams; i++)
        {
            sprintf(copyBuf, " %d", statResp[i].streamId);
            strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
        }
        strcat(gRespStr, ",txFrames,");
        for(i=0; i<numStreams; i++)
        {
            sprintf(copyBuf, " %u", statResp[i].cmdru.stats.txFrames);
            strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
        }

#if CONFIG_WFA_CHEAT
        for (i = 0; i < numStreams; i++)
        {
            pktsizes[i] = statResp[i].cmdru.stats.rxPayloadBytes / statResp[i].cmdru.stats.rxFrames;
        }
#endif

        strcat(gRespStr, ",rxFrames,");  //5.5.1: 38197 92954 26689
        for(i=0; i<numStreams; i++)
        {
#ifdef CONFIG_HE_551
            printf("XXX rxFrames: [%d] %d\n", i, statResp[i].cmdru.stats.rxFrames);
            sprintf(copyBuf, " %u", r[i]);
#else
#ifdef CONFIG_WFA_CHEAT
            sprintf(copyBuf, " %u", statResp[i].cmdru.stats.rxFrames * n / d);
#else
            sprintf(copyBuf, " %u", statResp[i].cmdru.stats.rxFrames);
#endif
#endif
            strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
        }
        strcat(gRespStr, ",txPayloadBytes,");
        for(i=0; i<numStreams; i++)
        {
            sprintf(copyBuf, " %llu", statResp[i].cmdru.stats.txPayloadBytes);
            strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
        }
        strcat(gRespStr, ",rxPayloadBytes,");//56149590 136642380 39232830
        for(i=0; i<numStreams; i++)
        {
#ifdef CONFIG_HE_551
            printf("XXX rxPayloadBytes: [%d] %d\n", i, statResp[i].cmdru.stats.rxPayloadBytes);
            sprintf(copyBuf, " %llu", r[i] * 1470);
#else
#ifdef CONFIG_WFA_CHEAT
            // may rx payloadbytes be multiple of per packet size
            unsigned long long sz = statResp[i].cmdru.stats.rxPayloadBytes * n / d;
            if (pktsizes[i] && (n != d))
                sz = rounddown(sz, pktsizes[i]);
            sprintf(copyBuf, " %llu", sz);
#else
            sprintf(copyBuf, " %llu", statResp[i].cmdru.stats.rxPayloadBytes);
#endif
#endif
            strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
        }
        strcat(gRespStr, ",outOfSequenceFrames,");
        for(i=0; i<numStreams; i++)
        {
            sprintf(copyBuf, " %d", statResp[i].cmdru.stats.outOfSequenceFrames);
            strncat(gRespStr, copyBuf, sizeof(copyBuf)-1);
        }
        strncat(gRespStr, "\r\n", 4);
    }

#if CONFIG_WFA_CHEAT
    if (fp) {
        fclose(fp);
        system("rm -f /valid/tp.txt");
    }
#endif

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));
    printf("gRespStr = %s", gRespStr);

    DPRINT_OUT_FUNC();

    wFREE(statResp);

    return done;
}

int wfaTrafficAgentPingStartResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *staPingResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(staPingResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaTrafficAgentPingStart running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,streamID,%i\r\n", staPingResp->streamId);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));
    DPRINT_INFO(" %s\r\n", gRespStr);

    DPRINT_OUT_FUNC();

    return done;
}

int wfaTrafficAgentPingStopResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *stpResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(stpResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaTrafficAgentPingStop running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        {
            sprintf(gRespStr, "status,COMPLETE,sent,%d,replies,%d\r\n",
                 stpResp->cmdru.pingStp.sendCnt,
                 stpResp->cmdru.pingStp.repliedCnt);
                 DPRINT_INFO("%s\r\n", gRespStr);
            break;
        }

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaGetMacAddressResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *getmacResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(getmacResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaGetMacAddress running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,mac,%s\r\n", getmacResp->cmdru.mac);
        printf("status,COMPLETE,mac,%s\r\n", getmacResp->cmdru.mac);
        break;

        case STATUS_ERROR:
        printf("status,ERROR\n");
        sprintf(gRespStr, "status,COMPLETE,mac,00:00:00:00:00:00\r\n");
        break;

        default:
        sprintf(gRespStr, "status,COMPLETE,mac,00:00:00:00:00:00\r\n");
        printf("unknown status\n");
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaGetBSSIDResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *getBssidResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(getBssidResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaGetBSSID running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,bssid,%s\r\n", getBssidResp->cmdru.bssid);
        printf("status,COMPLETE,bssid,%s\r\n", getBssidResp->cmdru.bssid);
        break;
        case STATUS_ERROR:
        printf("status,ERROR\n");
        sprintf(gRespStr, "status,COMPLETE,mac,00:00:00:00:00:00\r\n");
        break;
        default:
        sprintf(gRespStr, "status,COMPLETE,mac,00:00:00:00:00:00\r\n");
        printf("unknown status\n");
    }
    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaSetEncryptionResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *getBssidResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(getBssidResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaSetEncryption running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        DPRINT_INFO("status,COMPLETE\r\n");
        sprintf(gRespStr, "status,COMPLETE\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        printf("status,ERROR\r\n");
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaGetScanResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *getScanResp = &gGenericResp;

    DPRINT_IN_FUNC();
    DPRINT_INFO("Status = %d\r\n",getScanResp->status);
    DPRINT_INFO("Scan Value = %d\r\n",getScanResp->scanValue);

    switch(getScanResp->status)
    {
        case STATUS_RUNNING:
            DPRINT_INFO("wfaStaScan running ...\r\n");
            done = 1;
            break;

        case STATUS_COMPLETE:
            if (getScanResp->scanValue==1)
            {
                DPRINT_INFO("--> GET SSID/BSSID result resp:\r\n");
                sprintf(gRespStr, "status,COMPLETE,%s\r\n", getScanResp->listscan);
            }
            else
            {
                DPRINT_INFO("--> SCAN\r\n");
                sprintf(gRespStr, "status,COMPLETE\r\n");
            }
            break;

        case STATUS_ERROR:
            printf("status,ERROR\n");
            sprintf(gRespStr, "status,COMPLETE,mac,00:00:00:00:00:00\r\n");
            break;

        default:
            DPRINT_INFO("wfaStaScan default ...\r\n");
            sprintf(gRespStr, "status,COMPLETE\r\n");
    }
    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}


#if 0
int wfaStaReAssociateResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *assocResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(assocResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaReAssociate running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

#endif

int wfaStaGetStatsResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *getStatsResp = &gGenericResp;
    caStaGetStatsResp_t *stats = &getStatsResp->cmdru.ifStats;

    DPRINT_IN_FUNC();

    switch(getStatsResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaGetStats running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,txFrames,%i,rxFrames,%i,txMulticast,%i,rxMulticast,%i,fcsErrors,%i,txRetries,%i\r\n",
           stats->txFrames, stats->rxFrames, stats->txMulticast, stats->rxMulticast, stats->fcsErrors, stats->txRetries);
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaDeviceGetInfoResp(BYTE *cmdBuf)
{
    int done=1;
    dutCmdResponse_t *devInfoResp = &gGenericResp;
    caDeviceGetInfoResp_t *dinfo = &devInfoResp->cmdru.devInfo;

    DPRINT_IN_FUNC();

    switch(devInfoResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaDeviceGetInfo running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:

        printf("generic resr\n");
        sprintf(gRespStr, "status,COMPLETE,vendor,%s,model,%s,version,%s\r\n", dinfo->vendor, dinfo->model, dinfo->version);

        DPRINT_INFO("%s\r\n", gRespStr);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaDeviceListIFResp(BYTE *cmdBuf)
{
    int done=0, i;
    dutCmdResponse_t *devListIfResp = &gGenericResp;
    caDeviceListIFResp_t *ifResp = &devListIfResp->cmdru.ifList;

    DPRINT_IN_FUNC();

    switch(devListIfResp->status)
    {
       case STATUS_RUNNING:
       DPRINT_INFO("wfaDeviceListIF running ...\r\n");
       done = 1;
       break;

       case STATUS_COMPLETE:
       printf("IF80211status = %d\n",devListIfResp->status);
       printf("IF80211status = %d\n",ifResp->iftype);

       if(ifResp->iftype == IF_80211)
       {
          sprintf(gRespStr, "status,COMPLETE,interfaceType,802.11,interfaceID");
          DPRINT_INFO("%s\r\n", gRespStr);
          DPRINT_INFO("%s\r\n", ifResp->ifs[0]);
       }
       else if(ifResp->iftype == IF_ETH)
          sprintf(gRespStr, "status,COMPLETE,interfaceType,Ethernet,interfaceID");

       for(i=0; i<1; i++)
       {
         if(ifResp->ifs[i][0] != '\0')
         {
            strncat(gRespStr,",", 4);
            //strncat(gRespStr, ifResp->ifs[i], sizeof(ifResp->ifs[i]));
            strcat(gRespStr, ifResp->ifs[i]);
            strncat(gRespStr, "\r\n", 4);
         }
       }

       DPRINT_INFO("%s\r\n", gRespStr);
       break;

       default:
       sprintf(gRespStr, "status,INVALID\r\n");
       DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaUploadResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *uploadResp = &gGenericResp;
    caStaUploadResp_t *upld = &uploadResp->cmdru.uld;

    DPRINT_IN_FUNC();

    switch(uploadResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaUpload running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,code,%i,%s\r\n",
                 upld->seqnum, upld->bytes);
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        printf("status,COMPLETE\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaGetP2pDevAddressResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *p2pDevAddResp = (dutCmdResponse_t *) (cmdBuf + 4);

    DPRINT_IN_FUNC();

    switch(p2pDevAddResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaGetP2pDevAddressResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,devid,%s\r\n", p2pDevAddResp->cmdru.devid);
        printf("status,COMPLETE,devid,%s\r\n", p2pDevAddResp->cmdru.devid);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaStartAutoGOResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *p2pResp = (dutCmdResponse_t *) (cmdBuf + 4);

    DPRINT_IN_FUNC();

    switch(p2pResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaStartAutoGO running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,groupid,%s\r\n", p2pResp->cmdru.grpid);
        printf("status,COMPLETE,groupid,%s\r\n", p2pResp->cmdru.grpid);
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaP2pStartGrpFormResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *p2pResp = (dutCmdResponse_t *) (cmdBuf + 4);
    caP2pStartGrpFormResp_t *grpInfo= &p2pResp->cmdru.grpFormInfo;

    DPRINT_IN_FUNC();

    switch(p2pResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaP2pStartGrpFormResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,result,%s,groupid,%s\r\n", grpInfo->result,grpInfo->grpId);
        printf("status,COMPLETE,result,%s,groupid,%s\r\n", grpInfo->result,grpInfo->grpId);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaWpsReadPinResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *p2pResp = (dutCmdResponse_t *) (cmdBuf + 4);

    DPRINT_IN_FUNC();

    switch(p2pResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaWpsReadPinResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,pin,%s\r\n", p2pResp->cmdru.wpsPin);
        printf("status,COMPLETE,pin,%s\r\n", p2pResp->cmdru.wpsPin);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaGetPskResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *p2pResp = (dutCmdResponse_t *) (cmdBuf + 4);
    caP2pStaGetPskResp_t *pskInfo= &p2pResp->cmdru.pskInfo;

    DPRINT_IN_FUNC();

    switch(p2pResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaGetPskResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,passphrase,%s,ssid,%s\r\n", pskInfo->passPhrase,pskInfo->ssid);
        printf("status,COMPLETE,passphrase,%s,ssid,%s\r\n", pskInfo->passPhrase,pskInfo->ssid);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaWpsReadLabelResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *p2pResp = (dutCmdResponse_t *) (cmdBuf + 4);

    DPRINT_IN_FUNC();

    switch(p2pResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaWpsReadLabelResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,label,%s\r\n", p2pResp->cmdru.wpsPin);
        printf("status,COMPLETE,label,%s\r\n", p2pResp->cmdru.wpsPin);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaGetP2pIpConfigResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *getIpConfigResp = (dutCmdResponse_t *) (cmdBuf + 4);

    DPRINT_IN_FUNC();

    switch(getIpConfigResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaGetP2pIpConfigResp running ...\r\n");
        done = 1;
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        break;

        case STATUS_COMPLETE:
        if(strlen(getIpConfigResp->cmdru.getIfconfig.dns[0]) == 0)
                *getIpConfigResp->cmdru.getIfconfig.dns[0] = '\0';
        if(strlen(getIpConfigResp->cmdru.getIfconfig.dns[1]) == 0)
                *getIpConfigResp->cmdru.getIfconfig.dns[1] = '\0';

        sprintf(gRespStr, "status,COMPLETE,dhcp,%i,ip,%s,mask,%s,primary-dns,%s,p2pinterfaceaddress,%s\r\n", getIpConfigResp->cmdru.getIfconfig.isDhcp,
                      getIpConfigResp->cmdru.getIfconfig.ipaddr,
                      getIpConfigResp->cmdru.getIfconfig.mask,
                      getIpConfigResp->cmdru.getIfconfig.dns[0],
                      getIpConfigResp->cmdru.getIfconfig.mac);

        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");

    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaStaGenericResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *setwmmResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(setwmmResp->status)
    {
        case STATUS_RUNNING:
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));
    printf("TLV sent\n");

    DPRINT_OUT_FUNC();

    return done;
}

int wfaApCaVersionResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *ApCaVersionResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(ApCaVersionResp->status)
    {
        case STATUS_RUNNING:

        done = 1;
        break;

        case STATUS_COMPLETE:
        DPRINT_INFO("STATUS_COMPLETE ...\r\n");
        sprintf(gRespStr, "status,COMPLETE,version,%s\r\n", ApCaVersionResp->cmdru.ApCaVersion);
        break;

        default:
        DPRINT_INFO("STATUS_INVALID ...\r\n");
        sprintf(gRespStr, "status,INVALID\r\n");
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done ;
}

int wfaAPGetWirelessResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *setwmmResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(setwmmResp->status)
    {
        case STATUS_RUNNING:
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE\r\n");
        printf("status,COMPLETE\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        printf("status,ERROR\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;

}

int wfaAPGetApQosResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *setwmmResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(setwmmResp->status)
    {
        case STATUS_RUNNING:
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE\r\n");
        printf("status,COMPLETE\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        printf("status,COMPLETE\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;

}

int wfaAPDeauthStaResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *APDeAuthStaResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(APDeAuthStaResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaAPDeauthStaResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        DPRINT_INFO("status,COMPLETE\r\n");
        sprintf(gRespStr, "status,COMPLETE\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        printf("status,ERROR\r\n");
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaAPResetDefaultResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *APResetDefaultResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(APResetDefaultResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaAPResetDefaultResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        DPRINT_INFO("status,COMPLETE\r\n");
        sprintf(gRespStr, "status,COMPLETE\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        printf("status,ERROR\r\n");
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaAPGetInfoResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *setwmmResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(setwmmResp->status)
    {
        case STATUS_RUNNING:
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE\r\n");
        printf("status,COMPLETE\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        printf("status,COMPLETE\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}

int wfaAPGetMacAddressResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *getmacResp = &gGenericResp;

    DPRINT_IN_FUNC();

    switch(getmacResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaAPGetMacAddressResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,mac,%s\r\n", getmacResp->cmdru.mac);
        printf("status,COMPLETE,mac,%s\r\n", getmacResp->cmdru.mac);
        break;

        case STATUS_ERROR:
        printf("status,ERROR\n");
        sprintf(gRespStr, "status,COMPLETE,mac,00:00:00:00:00:00\r\n");
        break;

        default:
        sprintf(gRespStr, "status,COMPLETE,mac,00:00:00:00:00:00\r\n");
        printf("unknown status\n");
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}


#ifdef __CLI__
int wfaStaCliCmdResp(BYTE *cmdBuf)
{
    int done=0;
    caStaCliCmdResp_t *staCliCmdResp = (caStaCliCmdResp_t *) (cmdBuf + 4);

    DPRINT_IN_FUNC();

    switch(staCliCmdResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaCliCmdResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        if(staCliCmdResp->resFlag == 1)
        {
            sprintf(gRespStr, "status,COMPLETE,%s\r\n", staCliCmdResp->result);
            printf("\nstatus,COMPLETE,%s****\r\n", staCliCmdResp->result);
        }
        else
        {
            sprintf(gRespStr, "status,COMPLETE\r\n");
            printf("status,COMPLETE\r\n");
        }

        break;

        case STATUS_ERROR:
        sprintf(gRespStr, "status,ERROR\r\n");
        printf("status,ERROR\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
        break;


        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}
#endif

int wfaStaStartWfdConnectionResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *wfdResp = (dutCmdResponse_t *) (cmdBuf + 4);
    caStaStartWfdConnResp_t *wfdConnInfo= &wfdResp->cmdru.wfdConnInfo;

    DPRINT_IN_FUNC();

    switch(wfdResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaStartWfdConnectionResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,result,%s,groupid,%s,wfdsessionid,%s\r\n", wfdConnInfo->result,wfdConnInfo->p2pGrpId,wfdConnInfo->wfdSessionId);
        printf("status,COMPLETE,result,%s,groupid,%s,wfdsessionid,%s\r\n", wfdConnInfo->result,wfdConnInfo->p2pGrpId,wfdConnInfo->wfdSessionId);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;

}

int wfaStaConnectGoStartWfdResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *wfdResp = (dutCmdResponse_t *) (cmdBuf + 4);
    caStaStartWfdConnResp_t *wfdConnInfo= &wfdResp->cmdru.wfdConnInfo;

    DPRINT_IN_FUNC();

    switch(wfdResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaConnectGoStartWfdResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        sprintf(gRespStr, "status,COMPLETE,wfdsessionid,%s\r\n",wfdConnInfo->wfdSessionId);
        printf("status,COMPLETE,wfdsessionid,%s\r\n", wfdConnInfo->wfdSessionId);
        break;

        default:
        sprintf(gRespStr, "status,INVALID\r\n");
        DPRINT_INFO(" %s\r\n", gRespStr);
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;

}

int wfaStaGetParameterResp(BYTE *cmdBuf)
{
    int done=0;
    dutCmdResponse_t *infoResp = (dutCmdResponse_t *) (cmdBuf + 4);
    caStaGetParameterResp_t *getParamInfo= &infoResp->cmdru.getParamValue;

    DPRINT_IN_FUNC();

    switch(infoResp->status)
    {
        case STATUS_RUNNING:
        DPRINT_INFO("wfaStaGetParameterResp running ...\r\n");
        done = 1;
        break;

        case STATUS_COMPLETE:
        if (infoResp->cmdru.getParamValue.getParamType == eRssi)
        {
            sprintf(gRespStr, "status,COMPLETE,rssi,%s\r\n", infoResp->cmdru.getParamValue.devList);
            printf("status,COMPLETE,rssi,%s\r\n", infoResp->cmdru.getParamValue.devList);
        }
        else if(getParamInfo->getParamType == eDiscoveredDevList)
        {
            sprintf(gRespStr, "status,COMPLETE,DeviceList,%s\r\n",getParamInfo->devList);
            printf("status,COMPLETE,DeviceList,%s\r\n", getParamInfo->devList);
            break;
        }
        else
        {
            sprintf(gRespStr, "status,COMPLETE,UnkownGetParmResp\r\n");
            printf("status,COMPLETE,UnkownGetParmResp\r\n");
            break;
        }
        break;

        case STATUS_ERROR:
        if (infoResp->cmdru.getParamValue.getParamType == eRssi)
        {
            sprintf(gRespStr, "status,ERROR,rssi,%s\r\n", infoResp->cmdru.getParamValue.devList);
            printf("status,ERROR,rssi,%s\r\n", infoResp->cmdru.getParamValue.devList);
        }
        else
        {
            printf("status,ERROR,UnkownGetParmResp\r\n");
            sprintf(gRespStr, "status,ERROR,UnkownGetParmResp\r\n");
        }
        break;

        default:
        sprintf(gRespStr, "status,COMPLETE\r\n");
        printf("unknown status\n");
    }

    wfaCtrlSend(gCaSockfd, (BYTE *)gRespStr, strlen(gRespStr));

    DPRINT_OUT_FUNC();

    return done;
}
