#ifndef __BT_IPC_VENDOR_OPCODE_H__
#define __BT_IPC_VENDOR_OPCODE_H__

enum {
    BT_VENDOR_SUB_OPCODE_INIT = 0x0001,
    BT_VENDOR_SUB_OPCODE_DEINIT = 0x0002,
    BT_VENDOR_SUB_OPCODE_SETPWR = 0x0003,
    BT_VENDOR_SUB_OPCODE_BLE_CREATE_DB = 0x0004,
    BT_VENDOR_SUB_OPCODE_BLE_CREATE_ADV = 0x0005,
    BT_VENDOR_SUB_OPCODE_BLE_SET_ADV_DATA = 0x0006,
    BT_VENDOR_SUB_OPCODE_BLE_SET_SCAN_RSP_DATA = 0x0007,
    BT_VENDOR_SUB_OPCODE_BLE_START_ADV = 0x0008,
    BT_VENDOR_SUB_OPCODE_BLE_STOP_ADV = 0x0009,
    BT_VENDOR_SUB_OPCODE_BLE_DELETE_ADV = 0x000A,
    BT_VENDOR_SUB_OPCODE_BLE_SET_ADV_RANDOM_ADDR = 0x000B,
    BT_VENDOR_SUB_OPCODE_BLE_SET_NOTICE = 0x000C,
    BT_VENDOR_SUB_OPCODE_BLE_GET_IDLE_ACTV_IDX = 0x000D,
    BT_VENDOR_SUB_OPCODE_BLE_GET_MAX_ACTV_IDX = 0x000E,
    BT_VENDOR_SUB_OPCODE_BLE_CMD_EVT = 0x000F,
    BT_VENDOR_SUB_OPCODE_BLE_NOTICE_EVT = 0x0010,
    BT_VENDOR_SUB_OPCODE_BLE_QUERY_RSP = 0x0011,
    BT_VENDOR_SUB_OPCODE_BLE_READ_RESPONSE_VALUE = 0x0012,
    BT_VENDOR_SUB_OPCODE_BLE_UPDATE_PARAM = 0x0013,
    BT_VENDOR_SUB_OPCODE_BLE_GATT_MTU_CHANGE = 0x0014,
    BT_VENDOR_SUB_OPCODE_BLE_SET_MAX_MTU = 0x0015,
    BT_VENDOR_SUB_OPCODE_BLE_SEND_NOTI_VALUE = 0x0016,
    BT_VENDOR_SUB_OPCODE_BLE_SEND_IND_VALUE = 0x0017,
    BT_VENDOR_SUB_OPCODE_BLE_GET_CONNECT_STATE = 0x0018,
    BT_VENDOR_SUB_OPCODE_BLE_FIND_CONN_IDX_FROM_ADDR = 0x0019,
    BT_VENDOR_SUB_OPCODE_BLE_DISCONNECT = 0x001A,
    BT_VENDOR_SUB_OPCODE_BLE_GET_MAX_CONN_IDX = 0x001B,
    BT_VENDOR_SUB_OPCODE_BLE_FIND_ACTV_STATE_IDX = 0x001C,
    BT_VENDOR_SUB_OPCODE_BLE_FIND_MASTER_STATE_IDX = 0x001D,
    BT_VENDOR_SUB_OPCODE_BLE_GET_BT_ADDRESS = 0x001E,
    BT_VENDOR_SUB_OPCODE_BLE_FRAG = 0x001F,
    /* CP->AP: empty-payload command whose sole purpose is to be sent through
     * bt_ipc_mailbox_send_msg() so that, when AP is powered down, the state
     * machine slow path votes AP boot via bt_ipc_wakeup_ap(). AP side is
     * expected to drop/ignore this opcode -- AP recovery happens implicitly
     * by going through its normal boot/init sequence. */
    BT_VENDOR_SUB_OPCODE_AP_WAKEUP_TRIGGER = 0x0020,
    BT_VENDOR_SUB_OPCODE_BLE_DUT_START = 0x0021,
    BT_VENDOR_SUB_OPCODE_BLE_DUT_STOP = 0x0022,
    /* AP->CP: AP resumed from power-down with RAM retained. Transport is
     * intact, so this only tells CP the peer is alive again (flush pending).
     * Unlike INIT it MUST NOT trigger a full bk_bluetooth_init() on CP. */
    BT_VENDOR_SUB_OPCODE_AP_TRANSPORT_READY = 0x0023,
    BT_VENDOR_SUB_OPCODE_COUNT,
};

#endif
