#pragma once

#if !defined(CONFIG_H264D_GPU_DISPLAY_TEST_STREAM_1920X1080) && \
    !defined(CONFIG_H264D_GPU_DISPLAY_TEST_STREAM_1280X720) && \
    !defined(CONFIG_H264D_GPU_DISPLAY_TEST_STREAM_720X1280)
#define CONFIG_H264D_GPU_DISPLAY_TEST_STREAM_1920X1080 1
#endif

#ifdef CONFIG_H264D_GPU_DISPLAY_ENABLE_MIPI_DISPLAY
#define H264D_GPU_DISPLAY_ENABLE_MIPI_DISPLAY 1
#else
#define H264D_GPU_DISPLAY_ENABLE_MIPI_DISPLAY 0
#endif

#ifdef CONFIG_H264D_GPU_DISPLAY_ENABLE_ISP_PIP
#define H264D_GPU_DISPLAY_ENABLE_ISP_PIP 1
#else
#define H264D_GPU_DISPLAY_ENABLE_ISP_PIP 0
#endif

#if H264D_GPU_DISPLAY_ENABLE_ISP_PIP && defined(CONFIG_H264D_GPU_DISPLAY_ENABLE_ISP_PIP_ROTATE)
#define H264D_GPU_DISPLAY_ENABLE_ISP_PIP_ROTATE 1
#else
#define H264D_GPU_DISPLAY_ENABLE_ISP_PIP_ROTATE 0
#endif

#if H264D_GPU_DISPLAY_ENABLE_ISP_PIP_ROTATE
#if defined(CONFIG_H264D_GPU_DISPLAY_ISP_PIP_ROTATE_270)
#define H264D_GPU_DISPLAY_ISP_PIP_ROTATE_DEGREE 270U
#else
#define H264D_GPU_DISPLAY_ISP_PIP_ROTATE_DEGREE 90U
#endif
#else
#define H264D_GPU_DISPLAY_ISP_PIP_ROTATE_DEGREE 0U
#endif

#define H264D_GPU_DISPLAY_GPU_FLEXA_LINES       16U
#define H264D_GPU_DISPLAY_GPU_DISPLAY_WIDTH     1088U
#define H264D_GPU_DISPLAY_GPU_DISPLAY_HEIGHT    1920U

#ifdef CONFIG_H264D_GPU_DISPLAY_DPB_COVER
#define H264D_GPU_DISPLAY_DPB_COVER_ENABLE      1
#else
#define H264D_GPU_DISPLAY_DPB_COVER_ENABLE      0
#endif

/* Temporary A/B switch: keep decoder DPB cover on, disable GPU destination cover. */
#define H264D_GPU_DISPLAY_DEST_COVER_ENABLE     0

#if defined(CONFIG_H264D_GPU_DISPLAY_TEST_STREAM_1920X1080)
#define H264D_GPU_DISPLAY_TEST_STREAM_NAME      "1920x1080"
#define H264D_GPU_DISPLAY_TEST_STREAM_WIDTH     1920U
/* Match the Simple baseline and the decoder's macroblock-aligned output. */
#define H264D_GPU_DISPLAY_TEST_STREAM_HEIGHT    1088U
#define H264D_GPU_DISPLAY_GPU_ROTATE_DEGREE     90U
#define H264D_GPU_DISPLAY_GPU_DST_WIDTH         1920U
#define H264D_GPU_DISPLAY_GPU_DST_HEIGHT        1088U
#elif defined(CONFIG_H264D_GPU_DISPLAY_TEST_STREAM_1280X720)
#define H264D_GPU_DISPLAY_TEST_STREAM_NAME      "1280x720"
#define H264D_GPU_DISPLAY_TEST_STREAM_WIDTH     1280U
#define H264D_GPU_DISPLAY_TEST_STREAM_HEIGHT    720U
#define H264D_GPU_DISPLAY_GPU_ROTATE_DEGREE     90U
#define H264D_GPU_DISPLAY_GPU_DST_WIDTH         H264D_GPU_DISPLAY_GPU_DISPLAY_HEIGHT
#define H264D_GPU_DISPLAY_GPU_DST_HEIGHT        H264D_GPU_DISPLAY_GPU_DISPLAY_WIDTH
#else
#define H264D_GPU_DISPLAY_TEST_STREAM_NAME      "720x1280"
#define H264D_GPU_DISPLAY_TEST_STREAM_WIDTH     720U
#define H264D_GPU_DISPLAY_TEST_STREAM_HEIGHT    1280U
#define H264D_GPU_DISPLAY_GPU_ROTATE_DEGREE     0U
#define H264D_GPU_DISPLAY_GPU_DST_WIDTH         H264D_GPU_DISPLAY_GPU_DISPLAY_WIDTH
#define H264D_GPU_DISPLAY_GPU_DST_HEIGHT        H264D_GPU_DISPLAY_GPU_DISPLAY_HEIGHT
#endif

/*
 * H264 decoder post-processor (PP) scale test targets, used by the
 * start_dec_scale / start_dec_scale_cvt CLI commands. These exercise the
 * *decoder's own* scaler (out_width/out_height) and color-convert (out_format),
 * NOT the GPU blit path. The frame-mode controller decodes the native
 * 1280x720 / 720x1280 stream and lets the PP resize it to these targets.
 *
 * The frame-mode decoder PP produces these heights as-is (only NV12 is rounded
 * up to an even number), so the standard 16:9 targets 640x360 and 1920x1080
 * are used directly. The DOWN target is a down-scale and the UP target is an
 * up-scale relative to the default 1280x720 stream; the PP supports both
 * directions independently per axis.
 */
#define H264D_GPU_DISPLAY_DEC_SCALE_DOWN_WIDTH   640U
#define H264D_GPU_DISPLAY_DEC_SCALE_DOWN_HEIGHT  360U
#define H264D_GPU_DISPLAY_DEC_SCALE_UP_WIDTH     1920U
#define H264D_GPU_DISPLAY_DEC_SCALE_UP_HEIGHT    1080U

/* ISP PIP defaults (used by CLI when arguments are omitted). */
#ifndef CONFIG_H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_WIDTH
#define CONFIG_H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_WIDTH    1280
#endif
#ifndef CONFIG_H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_HEIGHT
#define CONFIG_H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_HEIGHT   720
#endif
#ifndef CONFIG_H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_FPS
#define CONFIG_H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_FPS      20
#endif
#ifndef CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_WIDTH
/*
 * ISP outputs NV12 for the PIP path. Keep width on a 16-pixel
 * boundary for GPU/DMA-friendly stride alignment, and keep width/height
 * even because NV12 is 4:2:0.
 *
 * Default 640x360 = half of 1280x720 (sensor input), so the ISP
 * channel does an exact 2x2 down-scale without distortion or extra
 * filtering complexity.
 */
#define CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_WIDTH       640
#endif
#ifndef CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_HEIGHT
#define CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_HEIGHT      360
#endif
#ifndef CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_DST_X
#if H264D_GPU_DISPLAY_ENABLE_ISP_PIP_ROTATE
/*
 * 1088 - 360 - 32 = 696 -> right-anchored rotated PIP with a 32 px
 * margin on a 1088x1920 portrait panel. The default ISP output is
 * 640x360, but it is visibly 360x640 after 90/270-degree blit rotation.
 */
#define CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_DST_X       696
#else
/*
 * 1088 - 640 - 32 = 416 -> right-anchored PIP with a 32 px margin on a
 * 1088x1920 portrait panel, mirroring the WeChat self-view layout.
 */
#define CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_DST_X       416
#endif
#endif
#ifndef CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_DST_Y
#define CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_DST_Y       32
#endif

#define H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_WIDTH   ((uint16_t)CONFIG_H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_WIDTH)
#define H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_HEIGHT  ((uint16_t)CONFIG_H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_HEIGHT)
#define H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_FPS     ((uint16_t)CONFIG_H264D_GPU_DISPLAY_ISP_SENSOR_DEFAULT_FPS)
#define H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_WIDTH      ((uint16_t)CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_WIDTH)
#define H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_HEIGHT     ((uint16_t)CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_HEIGHT)
#define H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_DST_X      ((uint16_t)CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_DST_X)
#define H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_DST_Y      ((uint16_t)CONFIG_H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_DST_Y)

#if H264D_GPU_DISPLAY_ISP_PIP_ROTATE_DEGREE == 90U || H264D_GPU_DISPLAY_ISP_PIP_ROTATE_DEGREE == 270U
#define H264D_GPU_DISPLAY_ISP_PIP_VISIBLE_WIDTH      H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_HEIGHT
#define H264D_GPU_DISPLAY_ISP_PIP_VISIBLE_HEIGHT     H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_WIDTH
#else
#define H264D_GPU_DISPLAY_ISP_PIP_VISIBLE_WIDTH      H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_WIDTH
#define H264D_GPU_DISPLAY_ISP_PIP_VISIBLE_HEIGHT     H264D_GPU_DISPLAY_ISP_PIP_DEFAULT_HEIGHT
#endif
