// Copyright 2021-2022 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <soc/soc.h>
#include "aon_pmu_types.h"
#include "sys_hw.h"

#ifdef __cplusplus
extern "C" {
#endif

//int_0_31_en DIRTY define
#define DMA0_NSEC_INTERRUPT_CTRL_BIT   (1 << 0)
#define ENCP_SEC_INTERRUPT_CTRL_BIT    (1 << 1)
#define ENCP_NSEC_INTERRUPT_CTRL_BIT   (1 << 2)
#define TIMER_INTERRUPT_CTRL_BIT       (1 << 3)
#define UART0_INTERRUPT_CTRL_BIT       (1 << 4)
#define PWM_INTERRUPT_CTRL_BIT         (1 << 5)
#define I2C_INTERRUPT_CTRL_BIT         (1 << 6)
#define SPI_INTERRUPT_CTRL_BIT         (1 << 7)
#define SADC_INTERRUPT_CTRL_BIT        (1 << 8)
#define IRDA_INTERRUPT_CTRL_BIT        (1 << 9)
#define SDIO_INTERRUPT_CTRL_BIT        (1 << SYS_CPU0_INT_0_31_EN_CPU0_SDIO_INT_EN_POS)
#define GDMA_INTERRUPT_CTRL_BIT        (1 << 11)
#define LA_INTERRUPT_CTRL_BIT          (1 << 12)
#define TIMER1_INTERRUPT_CTRL_BIT      (1 << (58 - 32))
#define I2C1_INTERRUPT_CTRL_BIT        (1 << SYS_CPU0_INT_0_31_EN_CPU0_I2C1_INT_EN_POS)
#define UART1_INTERRUPT_CTRL_BIT       (1 << 15)
#define UART2_INTERRUPT_CTRL_BIT       (1 << (56 - 32))
#define SPI1_INTERRUPT_CTRL_BIT        (1 << (57 - 32))
#define CAN_INTERRUPT_CTRL_BIT         (1 << 18)
#define USB_INTERRUPT_CTRL_BIT         (1 << SYS_CPU0_INT_0_31_EN_CPU0_USB_INT_EN_POS)
#define QSPI0_INTERRUPT_CTRL_BIT       (1 << SYS_CPU0_INT_0_31_EN_CPU0_QSPI0_INT_EN_POS)
#define CKMN_INTERRUPT_CTRL_BIT        (1 << SYS_CPU0_INT_0_31_EN_CPU0_CKMN_INT_EN_POS)
#define SBC_INTERRUPT_CTRL_BIT         (1 << SYS_CPU0_INT_0_31_EN_CPU0_SBC_INT_EN_POS)
#define AUD_INTERRUPT_CTRL_BIT         (1 << SYS_CPU0_INT_0_31_EN_CPU0_AUD_INT_EN_POS)
#define I2S_INTERRUPT_CTRL_BIT         (1 << SYS_CPU0_INT_0_31_EN_CPU0_I2S0_INT_EN_POS)
#if 0
#define WIFI_MODEM_EN                  (1 << SYS_CPU0_INT_0_31_EN_CPU0_WIFI_INT_PHY_MPB_EN_POS)
#define WIFI_MODEM_RC_EN               (1 << SYS_CPU0_INT_0_31_EN_CPU0_WIFI_INT_PHY_RIU_EN_POS)
#define WIFI_MAC_TX_RX_TIMER_INT_BIT   (1 << SYS_CPU0_INT_0_31_EN_CPU0_WIFI_MAC_INT_TX_RX_TIMER_EN_POS)

//int_32_63_en
#define WIFI_MAC_TX_RX_MISC_INT_BIT    (1 << SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_TX_RX_MISC_EN_POS)
#define WIFI_HSU_INTERRUPT_CTRL_BIT    (1 << SYS_CPU0_INT_32_63_EN_CPU0_WIFI_HSU_IRQ_EN_POS)
#define WIFI_MAC_RX_TRIGGER_INT_BIT    (1 << SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_RX_TRIGGER_EN_POS)
#define WIFI_MAC_TX_TRIGGER_INT_BIT    (1 << SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_TX_TRIGGER_EN_POS)
#define WIFI_MAC_PORT_TRIGGER_INT_BIT  (1 << SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_PROT_TRIGGER_EN_POS)
#define WIFI_MAC_GEN_INT_BIT           (1 << SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_GEN_EN_POS)
#define GPIO_NS_INTERRUPT_CTRL_BIT     (1 << SYS_CPU0_INT_32_63_EN_CPU0_GPIO_NS_EN_POS)
#define WIFI_MAC_WAKEUP_INT_BIT        (1 << SYS_CPU0_INT_32_63_EN_CPU0_WIFI_INT_MAC_WAKEUP_EN_POS)
#else
#define WIFI_MODEM_EN                  (1 << 29)
#define WIFI_MODEM_RC_EN               (1 << 30)
#define WIFI_MAC_TX_RX_TIMER_INT_BIT   (1 << 31)

//int_32_63_en
#define WIFI_MAC_TX_RX_MISC_INT_BIT    (1 << 0)
#define WIFI_HSU_INTERRUPT_CTRL_BIT    (1 << 0)
#define WIFI_MAC_RX_TRIGGER_INT_BIT    (1 << 1)
#define WIFI_MAC_TX_TRIGGER_INT_BIT    (1 << 2)
#define WIFI_MAC_PORT_TRIGGER_INT_BIT  (1 << 3)
#define WIFI_MAC_GEN_INT_BIT           (1 << 4)
#define GPIO_NS_INTERRUPT_CTRL_BIT     (1 << 5)
#define WIFI_MAC_WAKEUP_INT_BIT        (1 << 6)
#endif

#define DM_INTERRUPT_CTRL_BIT          (1 << SYS_CPU0_INT_32_63_EN_CPU0_DM_IRQ_EN_POS)
#define BLE_INTERRUPT_CTRL_BIT         (1 << SYS_CPU0_INT_32_63_EN_CPU0_BLE_IRQ_EN_POS)
#define BT_INTERRUPT_CTRL_BIT          (1 << SYS_CPU0_INT_32_63_EN_CPU0_BT_IRQ_EN_POS)
#define QSPI1_INTERRUPT_CTRL_BIT       (1 << SYS_CPU0_INT_32_63_EN_CPU0_QSPI1_INT_EN_POS)
#define I2S1_INTERRUPT_CTRL_BIT        (1 << SYS_CPU0_INT_32_63_EN_CPU0_I2S1_INT_EN_POS)
#define I2S2_INTERRUPT_CTRL_BIT        (1 << SYS_CPU0_INT_32_63_EN_CPU0_I2S2_INT_EN_POS)
#define H264_INTERRUPT_CTRL_BIT        (1 << SYS_CPU0_INT_32_63_EN_CPU0_H264_INT_EN_POS)
#define SDMADC_INTERRUPT_CTRL_BIT      (1 << SYS_CPU0_INT_32_63_EN_CPU0_SDMADC_INT_EN_POS)
#define ETHERNET_INTERRUPT_CTRL_BIT    (1 << SYS_CPU0_INT_32_63_EN_CPU0_ETHERNET_INT_EN_POS)
#define SCALE0_INTERRUPT_CTRL_BIT      (1 << SYS_CPU0_INT_32_63_EN_CPU0_SCAL0_INT_EN_POS)
#define OTP_INTERRUPT_CTRL_BIT         (1 << SYS_CPU0_INT_32_63_EN_CPU0_OTP_INT_EN_POS)
#define DPLL_UNLOCK_INTERRUPT_CTRL_BIT (1 << SYS_CPU0_INT_32_63_EN_CPU0_DPLL_UNLOCK_INT_EN_POS)
#define DCO_UNLOCK_INTERRUPT_CTRL_BIT  (1 << SYS_CPU0_INT_32_63_EN_CPU0_DCO_UNLOCK_INT_EN_POS)
#define TOUCHED_INTERRUPT_CTRL_BIT     (1 << SYS_CPU0_INT_32_63_EN_CPU0_TOUCHED_INT_EN_POS)
#define USBPLUG_INTERRUPT_CTRL_BIT     (1 << SYS_CPU0_INT_32_63_EN_CPU0_USBPLUG_INT_EN_POS)
#define RTC_INTERRUPT_CTRL_BIT         (1 << (54 - 32))
#define GPIO_INTERRUPT_CTRL_BIT        (1 << (55 - 32))
#define DMA1_SEC_INTERRUPT_CTRL_BIT    (1 << 0)
#define DMA1_NSEC_INTERRUPT_CTRL_BIT   (1 << 0)
#define YUV_BUF_INTERRUPT_CTRL_BIT     (1 << SYS_CPU0_INT_32_63_EN_CPU0_YUVB_INT_EN_POS)
#define ROTT_INTERRUPT_CTRL_BIT        (1 << SYS_CPU0_INT_32_63_EN_CPU0_ROTT_INT_EN_POS)
#define BK_7816_INTERRUPT_CTRL_BIT     (1 << SYS_CPU0_INT_32_63_EN_7816_INT_EN_POS)
#define LIN_INTERRUPT_CTRL_BIT         (1 << SYS_CPU0_INT_32_63_EN_LIN_INT_EN_POS)
#define SCALE1_INTERRUPT_CTRL_BIT      (1 << SYS_CPU0_INT_32_63_EN_SCAL1_INT_EN_POS)
#define MAILBOX_INTERRUPT_CTRL_BIT     (1 << SYS_CPU0_INT_32_63_EN_MAILBOX_INT_EN_POS)


#ifdef CONFIG_EXTERN_32K
#define RTC_CLOCK_FREQ				(32768)
#else
#define RTC_CLOCK_FREQ				(32000)
#endif

#define RTC_TICKS_PER_1MS				((float)RTC_CLOCK_FREQ/1000)
#define LOW_POWER_DPLL_STABILITY_DELAY_TIME              (0.19) // 0.19ms(hardware need at least 180us,because making the precise it use 190us,it will additional add 6us or 2us(external) )
#define LOW_POWER_RESTORE_DELAY_TIME_HARDWARE            (0.65) //0.6ms,cpu 60M 0.51ms
#define LOW_POWER_XTAL_DPLL_STABILITY_DELAY_TIME  ((LOW_POWER_DPLL_STABILITY_DELAY_TIME+LOW_POWER_RESTORE_DELAY_TIME_HARDWARE)*1000)

#define LOW_POWER_26M_STABILITY_DELAY_TIME_HARDWARE      0//(1300)
#define LOW_POWER_DELAY_TIME_HARDWARE                    (500)
#define LOW_POWER_EXTERN_32K_HARDWARE                    (1300)

#define LOW_POWER_BOOTUP_RESTORE_TIME                    0//(1500+1200)//cpu 120Mhz

#define PM_SLEEP_WAKEUP_BOOT_TIME_HARDWARE_TO_BOOTLOADER (4100)//4.1ms
#define PM_SLEEP_WAKEUP_RESTORE_BACKUP_DATE_TIME         (1660)//1.66ms
#define PM_SLEEP_WAKEUP_COMSUME_ALL_TIME_TICKS           (((PM_SLEEP_WAKEUP_BOOT_TIME_HARDWARE_TO_BOOTLOADER + PM_SLEEP_WAKEUP_RESTORE_BACKUP_DATE_TIME) * RTC_CLOCK_FREQ + 500000) / 1000000)//unit: rtc tick, round from us

#define PM_POWER_ON_ROSC_STABILITY_TIME                  (TIMER_CLOCK_FREQ_XTAL*2)//about 2ms

/*unit:32k clk cycles
  first delay version is base on following configration*/
#define PM_DEFAULT_LOW_VOLTAGE_WAKEUP1_DELAY 3
#define PM_DEFAULT_LOW_VOLTAGE_WAKEUP2_DELAY 3
#define PM_DEFAULT_LOW_VOLTAGE_WAKEUP3_DELAY 3

/*current used wakeup delay*/
#define PM_CURRENT_LOW_VOLTAGE_WAKEUP1_DELAY 8
#define PM_CURRENT_LOW_VOLTAGE_WAKEUP2_DELAY 8
#define PM_CURRENT_LOW_VOLTAGE_WAKEUP3_DELAY 3

/*delta between default and current,need to add to wifi wakeup delay*/
#define PM_LOW_VOLTAGE_DELTA_WAKEUP_DELAY (int32_t)(PM_CURRENT_LOW_VOLTAGE_WAKEUP1_DELAY +\
                                                    PM_CURRENT_LOW_VOLTAGE_WAKEUP2_DELAY +\
                                                    PM_CURRENT_LOW_VOLTAGE_WAKEUP3_DELAY -\
                                                    PM_DEFAULT_LOW_VOLTAGE_WAKEUP1_DELAY -\
                                                    PM_DEFAULT_LOW_VOLTAGE_WAKEUP2_DELAY -\
                                                    PM_DEFAULT_LOW_VOLTAGE_WAKEUP3_DELAY)

//ceil()
#define PM_LOW_VOLTAGE_DELTA_WAKEUP_DELAY_IN_US PM_SLEEP_WAKEUP_BOOT_TIME_HARDWARE_TO_BOOTLOADER//((PM_LOW_VOLTAGE_DELTA_WAKEUP_DELAY*1000000+RTC_CLOCK_FREQ-1)/RTC_CLOCK_FREQ)

#define PM_CHIP_ID_HIGH_POS                              (16)
#define PM_CHIP_ID_MASK                                  (BK7259_CHIP_ID_SERIES_MASK)
#define PM_CHIP_ID_MPW                                   (BK7259_CHIP_ID_V2_MPW)
#define PM_CHIP_ID_MPW_V2_3                              (BK7259_CHIP_ID_V2_MPW)
#define PM_CHIP_ID_MPW_V4                                (BK7259_CHIP_ID_V2_MPW)
#define PM_CHIP_ID_MP_A                                  (BK7259_CHIP_ID_V3A)
#define PM_CHIP_ID_MP_B                                  (BK7259_CHIP_ID_V3B)

#define PM_CHIP_ID_MP_C                                  (0x23A40910)//keep using old code,it will be modify

#define PM_FREQUNCY_DIV_MAX                              (15)
#define PM_CLKSEL_CORE_MAX                               (3)
#define PM_FREQUNCY_DIV_BUS_MAX                          (1)
#define PM_FREQUNCY_DIV_CPU_MAX                          (1)

#define PM_MODULE_SUB_POWER_DOMAIN_MAX                   (32)
#define WAKEUP_SOURCE_MARK                               (0x7F)

#define PM_CLKSEL_CORE_26M                               (0)
#define PM_CLKSEL_CORE_DCO                               (1)
#define PM_CLKSEL_CORE_320M                              (2)
#define PM_CLKSEL_CORE_480M                              (3)

typedef struct {
	uint8_t enum_name;
	uint32_t freq;
	uint32_t reg_val;
} clk_src_t;

typedef struct {
	uint8_t enum_name;
	uint32_t div;
	uint32_t reg_val;
} clk_div_t;

typedef enum
{
	UART_CLK_DIV_1 = 0,
	UART_CLK_DIV_2,
	UART_CLK_DIV_4,
	UART_CLK_DIV_8,
}uart_clk_div_t;

typedef enum
{
	FLASH_CLK_DIV_4 = 0,
	FLASH_CLK_DIV_6,
	FLASH_CLK_DIV_8,
	FLASH_CLK_DIV_10,
	FLASH_CLK_DIV_MAX,
}flash_clk_div_t;

typedef enum
{
	CKSEL_SYS_FLASH_XTAL = 0,
	CKSEL_SYS_FLASH_DCO = 1,
	CKSEL_SYS_FLASH_240M = 2,
	CKSEL_SYS_FLASH_320M = 3,
} cksel_sys_flash_t;

typedef enum
{
	CKSEL_SYS_AUXS_DCO = 0,
	CKSEL_SYS_AUXS_APLL = 1,
	CKSEL_SYS_AUXS_320M = 2,
	CKSEL_SYS_AUXS_480M = 3,
} cksel_sys_auxs_t;

typedef enum
{
	CKSEL_SYS_TIM_CLK32 = 0,
	CKSEL_SYS_TIM_XTAL = 1,
} cksel_sys_tim_t;

typedef enum
{
	CKSEL_SYS_XTAL_APLL_XTAL = 0,
	CKSEL_SYS_XTAL_APLL_APLL = 1,
} cksel_sys_xtal_apll_t;

typedef enum
{
	CKSEL_SYS_XTAL_160M_XTAL = 0,
	CKSEL_SYS_XTAL_160M_160M = 1,
} cksel_sys_xtal_160m_t;

typedef enum
{
	CKSEL_SYS_XTAL_120M_XTAL = 0,
	CKSEL_SYS_XTAL_120M_120M = 1,
} cksel_sys_xtal_120m_t;

typedef enum
{
	CKSEL_SYS_PWM0_XTAL = 0,
	CKSEL_SYS_PWM0_320M = 1,
} cksel_sys_pwm0_t;

typedef enum
{
	CKSEL_SYS_DCO_APLL_DCO = 0,
	CKSEL_SYS_DCO_APLL_APLL = 1,
} cksel_sys_dco_apll_t;

typedef enum
{
	CKSEL_SYS_TRACE_XTAL = 0,
	CKSEL_SYS_TRACE_320M = 1,
} cksel_sys_trace_t;

typedef enum
{
	FLASH_CLK_XTAL = 0,
	FLASH_CLK_DPLL,
	FLASH_CLK_APLL,
	FLASH_CLK_SRC_MAX,
}flash_clk_src_t;

typedef enum
{
	AUXLDOS_SEL_3V = 0,
	AUXLDOS_SEL_2P8V,
	AUXLDOS_SEL_1P8V,
	AUXLDOS_SEL_1P2V,
	AUXLDOS_SEL_NONE,
} auxldo_sel_t;


extern const clk_src_t flash_clk_src[];

extern const clk_div_t flash_clk_div[];

typedef enum {
	/* REG_0xC (Addr=0x44010030), value 0~31 -> bit 0~31 */
	CLK_PWR_ID_TIMER0 = 0,   /* bit0:  tim0_cken */
	CLK_PWR_ID_TIMER1 = 1,   /* bit1:  tim1_cken */
	CLK_PWR_ID_TIMER2 = 2,   /* bit2:  tim2_cken */
	CLK_PWR_ID_TIMER3 = 3,   /* bit3:  tim3_cken */
	CLK_PWR_ID_UART0  = 4,   /* bit4:  uart0_cken */
	CLK_PWR_ID_UART1  = 5,   /* bit5:  uart1_cken */
	CLK_PWR_ID_UART2  = 6,   /* bit6:  uart2_cken */
	CLK_PWR_ID_UART3  = 7,   /* bit7:  uart3_cken */
	CLK_PWR_ID_UART4  = 8,   /* bit8:  uart4_cken */
	CLK_PWR_ID_SPI0   = 9,   /* bit9:  spi0_cken */
	CLK_PWR_ID_SPI1   = 10,  /* bit10: spi1_cken */
	CLK_PWR_ID_SPI2   = 11,  /* bit11: spi2_cken */
	CLK_PWR_ID_SPI3   = 12,  /* bit12: spi3_cken */
	CLK_PWR_ID_SARADC = 13,  /* bit13: sadc_cken */
	CLK_PWR_ID_PWM0   = 14,  /* bit14: pwm0_cken */
	CLK_PWR_ID_OTP    = 15,  /* bit15: otp_cken */
	CLK_PWR_ID_I3C    = 16,  /* bit16: i3c_cken */
	CLK_PWR_ID_I2S0   = 17,  /* bit17: i2s0_cken */
	CLK_PWR_ID_I2S1   = 18,  /* bit18: i2s1_cken */
	CLK_PWR_ID_I2S2   = 19,  /* bit19: i2s2_cken */
	CLK_PWR_ID_I2S3   = 20,  /* bit20: i2s3_cken */
	CLK_PWR_ID_I2S4   = 21,  /* bit21: i2s4_cken */
	CLK_PWR_ID_I2C0   = 22,  /* bit22: i2c0_cken */
	CLK_PWR_ID_I2C3   = 23,  /* bit23: i2c3_cken */
	CLK_PWR_ID_IRDA0  = 24,  /* bit24: irda0_cken */
	CLK_PWR_ID_IRDA1  = 25,  /* bit25: irda1_cken */
	CLK_PWR_ID_IRDA2  = 26,  /* bit26: irda2_cken */
	CLK_PWR_ID_IRDA3  = 27,  /* bit27: irda3_cken */
	CLK_PWR_ID_CAN0   = 28,  /* bit28: can0_cken */
	CLK_PWR_ID_CAN1   = 29,  /* bit29: can1_cken */
	CLK_PWR_ID_LIN0   = 30,  /* bit30: lin0_cken */
	CLK_PWR_ID_SCR0   = 31,  /* bit31: scr0_cken */
	/* REG_0xD (Addr=0x44010034), value 32~62 -> bit 0~30 (bit18~21 reserved) */
	CLK_PWR_ID_AUDIO     = 32,  /* bit0:  audio_cken */
	CLK_PWR_ID_AUDIF0    = 33,  /* bit1:  audif0_cken */
	CLK_PWR_ID_AUDIF1    = 34,  /* bit2:  audif1_cken */
	CLK_PWR_ID_I2SO      = 35,  /* bit3:  i2so_cken */
	CLK_PWR_ID_CEC       = 36,  /* bit4:  cec_cken */
	CLK_PWR_ID_XDAC0     = 37,  /* bit5:  xdac0_cken */
	CLK_PWR_ID_XDAC1     = 38,  /* bit6:  xdac1_cken */
	CLK_PWR_ID_AUXS      = 39,  /* bit7:  auxs_cken */
	CLK_PWR_ID_AUXS_ENET = 40,  /* bit8:  auxs_enet_cken */
	CLK_PWR_ID_26MS      = 41,  /* bit9:  26ms_cken, 26MHz GPIO output */
	CLK_PWR_ID_32KS      = 42,  /* bit10: 32ks_cken, 32kHz */
	CLK_PWR_ID_26MO      = 43,  /* bit11: 26mo_cken, 26MHz div GPIO output */
	CLK_PWR_ID_240M     = 44,  /* bit12: 240m_cken */
	CLK_PWR_ID_320M     = 45,  /* bit13: 320m_cken */
	CLK_PWR_ID_480M     = 46,  /* bit14: 480m_cken */
	CLK_PWR_ID_160M     = 47,  /* bit15: 160m_cken */
	CLK_PWR_ID_120M     = 48,  /* bit16: 120m_cken, From 240M */
	CLK_PWR_ID_TRACE    = 49,  /* bit17: trace_cken */
	CLK_PWR_ID_WLSS     = 54,  /* bit22: wlss_cken (bit18~21 reserved) */
	CLK_PWR_ID_BTDM     = 55,  /* bit23: btdm_cken */
	CLK_PWR_ID_XVR      = 56,  /* bit24: xver_cken */
	CLK_PWR_ID_MAC      = 57,  /* bit25: mac_cken */
	CLK_PWR_ID_PHY      = 58,  /* bit26: phy_cken */
	CLK_PWR_ID_THREAD   = 59,  /* bit27: thread_cken */
	CLK_PWR_ID_BK24     = 60,  /* bit28: bk24_cken */
	CLK_PWR_ID_RF       = 61,  /* bit29: rf_cken */
	CLK_PWR_ID_OFDM     = 62,  /* bit30: ofdm_cken */

    /*after REG_0xA (Addr=0X48000028h), value 64~96 -> bit 0~30 (bit26~31 reserved) */
	CLK_PWR_ID_CPUA   = 64,   /* bit0:  cpua_cken, CPU时钟总开关 */
	CLK_PWR_ID_UART5  = 65,   /* bit1:  uart5_cken */
	CLK_PWR_ID_USB_HS = 66,   /* bit2:  usb_hs_cken */
	CLK_PWR_ID_PSRAM0 = 67,   /* bit3:  pram0_cken, psram0时钟使能 */
	CLK_PWR_ID_PSRAM1 = 68,   /* bit4:  pram1_cken, psram1时钟使能 */
	CLK_PWR_ID_QSPI0  = 69,   /* bit5:  qspi0_cken */
	CLK_PWR_ID_QSPI1  = 70,   /* bit6:  qspi1_cken */
	CLK_PWR_ID_SDIO0  = 71,   /* bit7:  sdio0_cken */
	CLK_PWR_ID_SDIO1  = 72,   /* bit8:  sdio1_cken */
	CLK_PWR_ID_CISP   = 73,   /* bit9:  cisp_cken */
	CLK_PWR_ID_GPU    = 74,   /* bit10: gpu_cken */
	CLK_PWR_ID_H26E   = 75,   /* bit11: h26e_cken */
	CLK_PWR_ID_CSI    = 76,   /* bit12: csi_cken */
	CLK_PWR_ID_DSI    = 77,   /* bit13: dsi_cken */
	CLK_PWR_ID_DPU    = 78,   /* bit14: dpu_cken */
	CLK_PWR_ID_USB_FS = 79,   /* bit15: usb_fs_cken */
	CLK_PWR_ID_CONF0  = 80,   /* bit16: conf0_cken, AhbPeri下配置时钟使能 */
	CLK_PWR_ID_CONF1  = 81,   /* bit17: conf1_cken, ISP下配置时钟使能 */
	CLK_PWR_ID_CONF2  = 82,   /* bit18: conf2_cken, H26E配置时钟使能 */
	CLK_PWR_ID_CONF3  = 83,   /* bit19: conf3_cken, VideoPost下配置时钟使能 */
	CLK_PWR_ID_CPU0   = 84,   /* bit20: cpu0_cken */
	CLK_PWR_ID_CPU1   = 85,   /* bit21: cpu1_cken */
	CLK_PWR_ID_NPU    = 86,   /* bit22: npu_cken */
	CLK_PWR_ID_TIMER4 = 87,   /* bit23: timer4_cken */
	CLK_PWR_ID_TIMER5 = 88,   /* bit24: timer5_cken */
	CLK_PWR_ID_TRACE_AP  = 89,   /* bit25: trace_cken, bit26~31 reserved */

	CLK_PWR_ID_NONE
} dev_clk_pwr_id_t;

typedef enum
{
	CLK_PWR_CTRL_PWR_DOWN = 0,
	CLK_PWR_CTRL_PWR_UP,
}dev_clk_pwr_ctrl_t;

/*
clock select for periphral unit
*/
typedef enum
{
	CLK_SEL_ID_26M = 0,
	CLK_SEL_ID_WDT,
	CLK_SEL_ID_SPI0,
	CLK_SEL_ID_SPI1,
	CLK_SEL_ID_QSPI0,
	CLK_SEL_ID_QSPI1,
	CLK_SEL_ID_DISP,
	CLK_SEL_ID_PSRAM,
	CLK_SEL_ID_SDIO,
	CLK_SEL_ID_AUXS,
	CLK_SEL_ID_FLASH,
	CLK_SEL_ID_I2S,
	CLK_SEL_ID_CORE,
	CLK_SEL_ID_UART0,
	CLK_SEL_ID_UART1,
	CLK_SEL_ID_UART2,
	CLK_SEL_ID_SADC,
	CLK_SEL_ID_PWM0,
	CLK_SEL_ID_PWM1,
	CLK_SEL_ID_TIMER0,
	CLK_SEL_ID_TIMER1,
	CLK_SEL_ID_TIMER2,
	CLK_SEL_ID_AUDIO,
	CLK_SEL_ID_JPEG,
}dev_clk_select_id_t;

typedef enum
{
	CLK_SEL_DCO = 0,
	CLK_SEL_XTL_26M,
	CLK_SEL_32K,
	CLK_SEL_APLL,
	CLK_SEL_DPLL,
	CLK_SEL_320M,
	CLK_SEL_480M,
}dev_clk_select_t;

typedef enum
{
	CLK_DIV_1 = 1,
	CLK_DIV_2 = 2,
	CLK_DIV_4 = 4,
	CLK_DIV_6 = 6,
	CLK_DIV_8 = 8,
	CLK_DIV_10 = 10,
	CLK_DIV_12 = 12,
	CLK_DIV_16 = 16,
	CLK_DIV_32 = 32,
	CLK_DIV_64 = 64,
	CLK_DIV_256 = 256,
}dev_clk_div_t;

typedef enum
{
	CLK_DCO_DIV_1 = 0,
	CLK_DCO_DIV_2,
	CLK_DCO_DIV_4,
	CLK_DCO_DIV_8
}dev_clk_dco_div_t;


/*clock power control end*/

/*power domain ctrl modules*/
typedef enum
{
	POWER_MODULE_NAME_MEM1 = 0,       //0
	POWER_MODULE_NAME_MEM2,           //1
	POWER_MODULE_NAME_MEM3,           //2
	POWER_MODULE_NAME_ENCP,           //3
	POWER_MODULE_NAME_BAKP,           //4
	POWER_MODULE_NAME_AHBP,           //5
	POWER_MODULE_NAME_AUDP,           //6
	POWER_MODULE_NAME_VIDP,           //7
	POWER_MODULE_NAME_BTSP,           //8
	POWER_MODULE_NAME_WIFIP_MAC,      //9
	POWER_MODULE_NAME_WIFI_PHY,       //10
	POWER_MODULE_NAME_MEM0,           //11
	POWER_MODULE_NAME_MEM4,           //12
	POWER_MODULE_NAME_OFDM,           //13
	POWER_MODULE_NAME_THREAD = 14,    //14
	POWER_MODULE_NAME_ROM_PGEN,       //15
	POWER_MODULE_NAME_TCM1_PGEN,      //16
	POWER_MODULE_NAME_CPU1 ,          //17
	POWER_MODULE_NAME_APP ,           //18
	POWER_MODULE_NAME_CPU2 ,          //19

	POWER_MODULE_NAME_BASE1 ,         //20
	POWER_DOMAIN_NAME_CP_CPU1_BAKP_AUDP,//21
	POWER_DOMAIN_NAME_VEHP_SPI_DEBUG,   //22
	POWER_DOMAIN_NAME_WRLP_ENCP,        //23
	POWER_DOMAIN_NAME_HSSUB_POWER,      //24
	POWER_DOMAIN_NAME_AP_CPU,           //25

	POWER_MODULE_NAME_NONE              //26
}power_module_name_t;

typedef enum
{
	POWER_SUB_MODULE_NAME_BAKP_TIMER1  = POWER_MODULE_NAME_BAKP*PM_MODULE_SUB_POWER_DOMAIN_MAX ,
	POWER_SUB_MODULE_NAME_BAKP_UART1 ,
	POWER_SUB_MODULE_NAME_BAKP_UART2 ,
	POWER_SUB_MODULE_NAME_BAKP_SPI1 ,
	POWER_SUB_MODULE_NAME_BAKP_I2C0 ,
	POWER_SUB_MODULE_NAME_BAKP_I2C1 ,
	POWER_SUB_MODULE_NAME_BAKP_SADC ,
	POWER_SUB_MODULE_NAME_BAKP_PWM1 ,
	POWER_SUB_MODULE_NAME_BAKP_PWM0 ,
	POWER_SUB_MODULE_NAME_BAKP_TRNG ,
	POWER_SUB_MODULE_NAME_BAKP_IRDA ,
	POWER_SUB_MODULE_NAME_BAKP_SDIO ,
	POWER_SUB_MODULE_NAME_BAKP_COMSEG ,
	POWER_SUB_MODULE_NAME_BAKP_DMA0 ,
	POWER_SUB_MODULE_NAME_BAKP_DMA1 ,
	POWER_SUB_MODULE_NAME_BAKP_LA ,
	POWER_SUB_MODULE_NAME_BAKP_UART3 ,
	POWER_SUB_MODULE_NAME_BAKP_I2S ,
	POWER_SUB_MODULE_NAME_BAKP_LEDC ,
	POWER_SUB_MODULE_NAME_BAKP_QSPI1 ,
	POWER_SUB_MODULE_NAME_BAKP_PSRAM ,
	POWER_SUB_MODULE_NAME_BAKP_XDAC0,
	POWER_SUB_MODULE_NAME_BAKP_XDAC1,
	POWER_SUB_MODULE_NAME_BAKP_PM ,
	POWER_SUB_MODULE_NAME_BAKP_NONE
}power_sub_module_name_bakp_e;

typedef enum
{
	POWER_SUB_MODULE_NAME_ENCP_OTP  = POWER_MODULE_NAME_ENCP*PM_MODULE_SUB_POWER_DOMAIN_MAX ,
	POWER_SUB_MODULE_NAME_ENCP_TRUSTENGINE ,
	POWER_SUB_MODULE_NAME_ENCP_NONE
}power_sub_module_name_encp_e;
typedef enum
{
	POWER_SUB_MODULE_NAME_AUDP_FFT  = POWER_MODULE_NAME_AUDP*PM_MODULE_SUB_POWER_DOMAIN_MAX ,
	POWER_SUB_MODULE_NAME_AUDP_SBC ,
	POWER_SUB_MODULE_NAME_AUDP_AUDIO ,
	POWER_SUB_MODULE_NAME_AUDP_I2S ,
	POWER_SUB_MODULE_NAME_AUDP_NONE
}power_sub_module_name_audp_e;

typedef enum
{
	POWER_SUB_MODULE_NAME_VIDP_JPEG_EN = POWER_MODULE_NAME_VIDP*PM_MODULE_SUB_POWER_DOMAIN_MAX,
	POWER_SUB_MODULE_NAME_VIDP_JPEG_DE ,
	POWER_SUB_MODULE_NAME_VIDP_DMA2D ,
	POWER_SUB_MODULE_NAME_VIDP_LCD ,
	POWER_SUB_MODULE_NAME_VIDP_YUVBUF ,
	POWER_SUB_MODULE_NAME_VIDP_ROTT ,
	POWER_SUB_MODULE_NAME_VIDP_SCAL0 ,
	POWER_SUB_MODULE_NAME_VIDP_SCAL1 ,
	POWER_SUB_MODULE_NAME_VIDP_H264 ,

	POWER_SUB_MODULE_NAME_VIDP_NONE
}power_sub_module_name_vidp_e;

typedef enum
{
	POWER_SUB_MODULE_NAME_BTSP = POWER_MODULE_NAME_BTSP*PM_MODULE_SUB_POWER_DOMAIN_MAX ,
	POWER_SUB_MODULE_NAME_BTSP_NONE
}power_sub_module_name_btsp_e;

typedef enum
{
	POWER_SUB_MODULE_NAME_THREAD = POWER_MODULE_NAME_THREAD*PM_MODULE_SUB_POWER_DOMAIN_MAX ,
	POWER_SUB_MODULE_NAME_THREAD_NONE
}power_sub_module_name_thread_e;

typedef enum
{
    POWER_SUB_MODULE_NAME_PHY_BT = POWER_MODULE_NAME_WIFI_PHY*PM_MODULE_SUB_POWER_DOMAIN_MAX ,
	POWER_SUB_MODULE_NAME_PHY_WIFI ,
	POWER_SUB_MODULE_NAME_PHY_RF ,
	POWER_SUB_MODULE_NAME_PHY_THREAD ,
	POWER_SUB_MODULE_NAME_PHY_NONE
}power_sub_module_name_phy_e;

typedef enum
{
	POWER_SUB_MODULE_NAME_AHBP_CAN = POWER_MODULE_NAME_AHBP*PM_MODULE_SUB_POWER_DOMAIN_MAX ,
	POWER_SUB_MODULE_NAME_AHBP_QSPI ,
	POWER_SUB_MODULE_NAME_AHBP_USB ,
	POWER_SUB_MODULE_NAME_AHBP_PSRAM ,
	POWER_SUB_MODULE_NAME_AHBP_QSPI1 ,
	POWER_SUB_MODULE_NAME_AHBP_ENET ,
	POWER_SUB_MODULE_NAME_AHBP_SCR ,
	POWER_SUB_MODULE_NAME_AHBP_LIN ,
	POWER_SUB_MODULE_NAME_AHBP_NONE
}power_sub_module_name_ahbp_e;

typedef enum
{
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_TIMER1 = POWER_DOMAIN_NAME_CP_CPU1_BAKP_AUDP*PM_MODULE_SUB_POWER_DOMAIN_MAX,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_UART1,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_UART2,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_UART3,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2C0,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2C1,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_SPI1,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_SPI2,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_SADC,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_PWM,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I3C,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_TIMER2,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_UART4,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_IPI,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_XDAC0,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_XDAC1,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_DMA0,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_MBOX,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_HSPL,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_AUD,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_SPDIF0,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_SPDIF1,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2S0,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2S1,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2S2,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2S3,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2S4,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_CEC,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_CPU1,
	POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_NONE
}power_sub_domain_name_cp_cpu1_bakp_audp_e;

typedef enum
{
	POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_LA = POWER_DOMAIN_NAME_VEHP_SPI_DEBUG*PM_MODULE_SUB_POWER_DOMAIN_MAX,
	POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_CAN0,
	POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_CAN1,
	POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_SCR0,
	POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_LIN0,
	POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_IRDA0,
	POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_IRDA1,
	POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_IRDA2,
	POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_IRDA3,
	POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_SPI_DEBUG,
	POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_NONE
}power_sub_domain_name_vehp_spi_debug_e;

typedef enum
{
	POWER_SUB_DOMAIN_NAME_WRLP_ENCP_BTDM = POWER_DOMAIN_NAME_WRLP_ENCP*PM_MODULE_SUB_POWER_DOMAIN_MAX,
	POWER_SUB_DOMAIN_NAME_WRLP_ENCP_BK24,
	POWER_SUB_DOMAIN_NAME_WRLP_ENCP_XVR,
	POWER_SUB_DOMAIN_NAME_WRLP_ENCP_MAC,
	POWER_SUB_DOMAIN_NAME_WRLP_ENCP_PHY,
	POWER_SUB_DOMAIN_NAME_WRLP_ENCP_THREAD,
	POWER_SUB_DOMAIN_NAME_WRLP_ENCP_SHANHAI,
	POWER_SUB_DOMAIN_NAME_WRLP_ENCP_OTP_AHB,
	POWER_SUB_DOMAIN_NAME_WRLP_ENCP_OTP_APB,
	POWER_SUB_DOMAIN_NAME_WRLP_ENCP_RF,
	POWER_SUB_DOMAIN_NAME_WRLP_ENCP_NONE
}power_sub_domain_name_wrlp_encp_e;

typedef enum
{
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_SYSCFG = POWER_DOMAIN_NAME_HSSUB_POWER*PM_MODULE_SUB_POWER_DOMAIN_MAX,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_MEMCHK,
	POWER_SUB_DOMAIN_NAME_HSUSB_POWER_QSPI0,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_QSPI1,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_SDIO0,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_SDIO1,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_PSRAM0,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_PSRAM1,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_ENET0,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_USB_FS,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_USB_HS,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_HSPL,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_PPHS,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_WWDT,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_UART5,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_TIMER4,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_TIMER5,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_ON,
	POWER_SUB_DOMAIN_NAME_HSSUB_POWER_NONE
}power_sub_domain_name_hssub_power_e;

typedef enum
{
	POWER_SUB_DOMAIN_NAME_AP_CPU = POWER_DOMAIN_NAME_AP_CPU*PM_MODULE_SUB_POWER_DOMAIN_MAX,
	POWER_SUB_DOMAIN_NAME_AP_CPU_NONE
}power_sub_domain_name_ap_cpu_e;

typedef enum
{
	POWER_MODULE_STATE_ON = 0,
    POWER_MODULE_STATE_OFF,
	POWER_MODULE_STATE_NONE
}power_module_state_t;
typedef enum
{
	POWER_MODULE_STATE_LOWVOL_ON = 0,
    POWER_MODULE_STATE_LOWVOL_OFF,
	POWER_MODULE_STATE_LOWVOL_NONE
}lowvol_module_state_t;
typedef enum
{
	ENTER_DEEP_SLEEP_DISABLE = 0,
    ENTER_DEEP_SLEEP_ENABLE,
	ENTER_DEEP_SLEEP_NONE
}enter_deepsleep_state_t;
typedef enum
{
	ENTER_LOW_VOLTAGE_DISABLE = 0,
    ENTER_LOW_VOLTAGE_ENABLE,
	ENTER_LOW_VOLTAGE_NONE
}enter_lowvoltage_state_t;

/*RF using owner modules*/
typedef enum
{
    MODULE_NAME_WIFI = 0,
	MODULE_NAME_BT,
	MODULE_NAME_NONE
}module_name_t;
typedef enum
{
	HIGH_FREQUECY_CLOCK_MODULE_CPU0 = 0,
	HIGH_FREQUECY_CLOCK_MODULE_CPU1,
	HIGH_FREQUECY_CLOCK_MODULE_CPU0_MATRIX,
	HIGH_FREQUECY_CLOCK_MODULE_CPU1_MATRIX,
	HIGH_FREQUECY_CLOCK_MODULE_SDIO,
	HIGH_FREQUECY_CLOCK_MODULE_QSPI,
	HIGH_FREQUECY_CLOCK_MODULE_PSRAM,
	HIGH_FREQUECY_CLOCK_MODULE_DISP,
	HIGH_FREQUECY_CLOCK_MODULE_JPEG,
	HIGH_FREQUECY_CLOCK_MODULE_FLASH,
	HIGH_FREQUECY_CLOCK_MODULE_USB,
	HIGH_FREQUECY_CLOCK_MODULE_NONE
}high_clock_module_name_t;
typedef enum
{
	WAKEUP_SOURCE_INT_GPIO = 0,
	WAKEUP_SOURCE_INT_RTC,
	WAKEUP_SOURCE_INT_WIFI,
	WAKEUP_SOURCE_INT_BT,
	WAKEUP_SOURCE_INT_USBPLUG,
	WAKEUP_SOURCE_INT_TOUCHED,
	WAKEUP_SOURCE_INT_VAD,
	WAKEUP_SOURCE_INT_NONE,
}wakeup_source_t;

typedef enum
{
	CHARGE_STEP1 = 0,
	CHARGE_STEP2,
	CHARGE_STEP3,
	CHARGE_STEP4,
} sys_drv_charge_step_t;
typedef enum
{
	ANALOG_REG0 = 0,
	ANALOG_REG1,
	ANALOG_REG2,
	ANALOG_REG3,
	ANALOG_REG4,
	ANALOG_REG5,
	ANALOG_REG6,
    ANALOG_REG7,
	ANALOG_REG8,
	ANALOG_REG9,
	ANALOG_REG10,
	ANALOG_REG11,
	ANALOG_REG12,
	ANALOG_REG13,
    ANALOG_REG14,
	ANALOG_REG15,
	ANALOG_REG16,
	ANALOG_REG17,
	ANALOG_REG18,
	ANALOG_REG19,
	ANALOG_REG20,
	ANALOG_REG21,
	ANALOG_REG22,
	ANALOG_REG23,
	ANALOG_REG24,
	ANALOG_REG25,
	ANALOG_REG26,
	ANALOG_REG27,
	ANALOG_REG28,
	ANALOG_REG29,
	ANALOG_REG30,
	ANALOG_REG31,
	ANALOG_REG32,
	ANALOG_REG33,
	ANALOG_REG34,
	ANALOG_REG35,
	ANALOG_REG36,
	ANALOG_REG37,
	ANALOG_REG38,
	ANALOG_REG39,
	ANALOG_REG40,
	ANALOG_REG41,
	ANALOG_REG42,
	ANALOG_REG43,
	ANALOG_REG44,
	ANALOG_REG45,
	ANALOG_REG46,
	ANALOG_REG47,
	ANALOG_REG48,
	ANALOG_MAX
} analog_reg_t;

typedef enum
{
	CLK_DIV_REG0 = 0,
	CLK_DIV_REG1,
	CLK_DIV_REG2,
	CLK_DIV_NONE
} clk_div_reg_e;
#define CLK_DIV_ADDRESS_MAP  \
{	\
	{CLK_DIV_REG0, SYS_CPU_CLK_DIV_MODE1_ADDR, }, \
	{CLK_DIV_REG1, SYS_CPU_CLK_DIV_MODE2_ADDR, }, \
	{CLK_DIV_REG2, SYS_CPU_CLK_DIV_MODE3_ADDR, }, \
}
typedef struct {
	clk_div_reg_e clk_div_reg;
	uint32_t reg_address;
} clk_div_address_map_t;
typedef enum
{
	PMU_REG0 = 0,
	PMU_REG2,
	PMU_REG3,
	PMU_REG4,
	PMU_REG5,
	PMU_REG0x25,
	PMU_REG0x40,
	PMU_REG0x41,
	PMU_REG0x42,
	PMU_REG0x43,
	PMU_REG0x70,
	PMU_REG0x71,
	PMU_REG0x74,
	PMU_REG0x75,
	PMU_REG0x78,
	PMU_REG0x79,
	PMU_REG0x7c,
	PMU_NONE
} pmu_reg_e;
#define PMU_ADDRESS_MAP  \
{	\
	{PMU_REG0, AON_PMU_R0_ADDR, }, \
	{PMU_REG2, AON_PMU_R2_ADDR, }, \
	{PMU_REG3, AON_PMU_R3_ADDR, }, \
	{PMU_REG4, AON_PMU_R4_ADDR, }, \
	{PMU_REG5, AON_PMU_R5_ADDR, }, \
	{PMU_REG0x25, AON_PMU_R25_ADDR, }, \
	{PMU_REG0x40, AON_PMU_R40_ADDR, }, \
	{PMU_REG0x41, AON_PMU_R41_ADDR, }, \
	{PMU_REG0x42, AON_PMU_R42_ADDR, }, \
	{PMU_REG0x43, AON_PMU_R43_ADDR, }, \
	{PMU_REG0x70, AON_PMU_R70_ADDR, }, \
	{PMU_REG0x71, AON_PMU_R71_ADDR, }, \
	{PMU_REG0x74, AON_PMU_R74_ADDR, }, \
	{PMU_REG0x75, AON_PMU_R75_ADDR, }, \
	{PMU_REG0x78, AON_PMU_R78_ADDR, }, \
	{PMU_REG0x79, AON_PMU_R79_ADDR, }, \
	{PMU_REG0x7c, AON_PMU_R7C_ADDR, }, \
}
typedef struct {
	pmu_reg_e pmu_reg;
	uint32_t reg_address;
}pmu_address_map_t;


typedef enum
{
    BIT_SLEEP_FLAG_DEEP_SLEEP    = 16,
    BIT_SLEEP_FLAG_LOW_VOLTAGE      ,
    BIT_SLEEP_FLAG_NONE
} bit_sleep_flag_e;

typedef enum
{
    SARADC_CLK_SRC_XTAL = 0,
    SARADC_CLK_SRC_APLL,
    SARADC_CLK_SRC_UNKNOW = 0xff
} sys_saradc_clk_sel_t;

typedef enum
{
    SPI_CLK_SRC_XTAL = 0,
    SPI_CLK_SRC_APLL,
    SPI_CLK_SRC_UNKNOW = 0xff
} sys_spi_clk_sel_t;

typedef enum
{
    PWM_CLK_SRC_32K = 0,
    PWM_CLK_SRC_XTAL,
    PWM_CLK_SRC_UNKNOW = 0xff
} sys_pwm_clk_sel_t;

typedef enum
{
	LOW_POWER_MODE_NORMAL_SLEEP = 0,
	LOW_POWER_MODE_LOW_VOLTAGE ,
	LOW_POWER_DEEP_SLEEP ,
	LOW_POWER_MODE_NONE
}low_power_sleep_mode_e;

typedef enum
{
	RF_CTRL_PTA = 0,
	RF_CTRL_WIFI,
	RF_CTRL_BT,
	RF_CTRL_THREAD,
}rf_ctrl_t;

typedef enum _dco_speed
{
	DCO_CALIB_SPEED_26M,
	DCO_CALIB_SPEED_60M,
	DCO_CALIB_SPEED_80M,
	DCO_CALIB_SPEED_120M,
	DCO_CALIB_SPEED_240M,
	DCO_CALIB_SPEED_320M,
	DCO_CALIB_SPEED_480M,
}dco_cali_speed_e;

typedef enum
{
	DIAG_DEBUG_BTS0 = 0, // btsp_debug[0:32]
	DIAG_DEBUG_BTS1,	 // btsp_debug[32+:32]
	DIAG_DEBUG_BTS2,	 // btsp_debug[64+:32]
	DIAG_DEBUG_BTS3,	 // btsp_debug[96+:6]
	DIAG_DEBUG_MAC, 	 // wifip_mac_dbg[31:0]
	DIAG_DEBUG_PHY, 	 // wifip_phy_dbg[31:0]
} diag_debug_mux_t;


#define pm_power_module_name_e                         unsigned int

/*----POWER DOMAIN DEFINE--------*/

#define PM_POWER_MODULE_NAME_BTSP                      (POWER_MODULE_NAME_BTSP) //8
#define PM_POWER_MODULE_NAME_WIFIP_MAC                 (POWER_MODULE_NAME_WIFIP_MAC)//9
#define PM_POWER_MODULE_NAME_PHY                       (POWER_MODULE_NAME_WIFI_PHY) //10

#define PM_POWER_MODULE_NAME_THREAD                    (POWER_MODULE_NAME_THREAD)   //14

#define PM_POWER_MODULE_NAME_CPU1                      (POWER_MODULE_NAME_CPU1)     //17
#define PM_POWER_MODULE_NAME_CPU2                      (POWER_MODULE_NAME_CPU2)     //18
#define PM_POWER_MODULE_NAME_APP                       (POWER_MODULE_NAME_APP)      //19
#define PM_POWER_MODULE_NAME_NONE                      (POWER_MODULE_NAME_NONE)     //20

#define PM_POWER_DOMAIN_0                              (POWER_DOMAIN_NAME_CP_CPU1_BAKP_AUDP)   /* Power domain 0 */
#define PM_POWER_DOMAIN_1                              (POWER_DOMAIN_NAME_VEHP_SPI_DEBUG)      /* Power domain 1 */
#define PM_POWER_DOMAIN_2                              (POWER_DOMAIN_NAME_WRLP_ENCP)           /* Power domain 2 */
#define PM_POWER_DOMAIN_3                              (POWER_DOMAIN_NAME_AP_CPU)              /* Power domain 3 */
#define PM_POWER_DOMAIN_4                              (POWER_DOMAIN_NAME_HSSUB_POWER)         /* Power domain 4 */


/*--------------previous project use macro defines, please don't use them  begin----------------------*/
/*----SUB POWER DOMAIN AUDP--------*/
#define PM_POWER_SUB_MODULE_NAME_AUDP_FFT              (POWER_SUB_MODULE_NAME_AUDP_FFT)
#define PM_POWER_SUB_MODULE_NAME_AUDP_SBC              (POWER_SUB_MODULE_NAME_AUDP_SBC)
#define PM_POWER_SUB_MODULE_NAME_AUDP_AUDIO            (POWER_SUB_MODULE_NAME_AUDP_AUDIO)
#define PM_POWER_SUB_MODULE_NAME_AUDP_I2S              (POWER_SUB_MODULE_NAME_AUDP_I2S)
/*----SUB POWER DOMAIN THREAD--------*/
#define PM_POWER_SUB_MODULE_NAME_THREAD                (POWER_SUB_MODULE_NAME_THREAD)
/*----SUB POWER DOMAIN PHY--------*/
#define PM_POWER_SUB_MODULE_NAME_PHY_THREAD            (POWER_SUB_MODULE_NAME_PHY_THREAD)
/*----SUB POWER DOMAIN AHB--------*/
#define PM_POWER_SUB_MODULE_NAME_AHBP_PSRAM            (POWER_SUB_MODULE_NAME_AHBP_PSRAM)
#define PM_POWER_SUB_MODULE_NAME_AHBP_ENET             (POWER_SUB_MODULE_NAME_AHBP_ENET)
#define PM_POWER_SUB_MODULE_NAME_AHBP_LIN              (POWER_SUB_MODULE_NAME_AHBP_LIN)
/*----SUB POWER DOMAIN BAKP--------*/
#define PM_POWER_SUB_MODULE_NAME_BAKP_TIMER1           (POWER_SUB_MODULE_NAME_BAKP_TIMER1)
#define PM_POWER_SUB_MODULE_NAME_BAKP_UART1            (POWER_SUB_MODULE_NAME_BAKP_UART1)
#define PM_POWER_SUB_MODULE_NAME_BAKP_UART2            (POWER_SUB_MODULE_NAME_BAKP_UART2)
#define PM_POWER_SUB_MODULE_NAME_BAKP_SADC             (POWER_SUB_MODULE_NAME_BAKP_SADC)
#define PM_POWER_SUB_MODULE_NAME_BAKP_PWM0             (POWER_SUB_MODULE_NAME_BAKP_PWM0)
#define PM_POWER_SUB_MODULE_NAME_BAKP_DMA0             (POWER_SUB_MODULE_NAME_BAKP_DMA0)
#define PM_POWER_SUB_MODULE_NAME_BAKP_DMA1             (POWER_SUB_MODULE_NAME_BAKP_DMA1)
#define PM_POWER_SUB_MODULE_NAME_BAKP_UART3            (POWER_SUB_MODULE_NAME_BAKP_UART3)
#define PM_POWER_SUB_MODULE_NAME_BAKP_XDAC0            (POWER_SUB_MODULE_NAME_BAKP_XDAC0)
#define PM_POWER_SUB_MODULE_NAME_BAKP_XDAC1            (POWER_SUB_MODULE_NAME_BAKP_XDAC1)
/*--------------previous project use macro defines, please don't use them  end----------------------*/

/*
 * PM_POWER_SUB_DOMAIN_* macros: defined in SOC HAL (sys_types.h), included above.
 * BLE / WIFI / other modules: only need to #include "pm.h" (or <modules/pm.h>);
 * sys_types.h is pulled in by pm.h, so PM_* and power domain types are available.
 * Each chip's sys_types.h defines its own sub-domain enums and PM_* mappings.
 */

/* PM module uses short names; map to enum above (SOC-specific, extend per chip) */
/* CP: sub domain cpu1 bakp audp */
#define PM_POWER_SUB_DOMAIN_TIMER1    (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_TIMER1)
#define PM_POWER_SUB_DOMAIN_UART1     (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_UART1)
#define PM_POWER_SUB_DOMAIN_UART2     (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_UART2)
#define PM_POWER_SUB_DOMAIN_UART3     (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_UART3)
#define PM_POWER_SUB_DOMAIN_I2C0      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2C0)
#define PM_POWER_SUB_DOMAIN_I2C1      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2C1)
#define PM_POWER_SUB_DOMAIN_SPI1      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_SPI1)
#define PM_POWER_SUB_DOMAIN_SPI2      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_SPI2)
#define PM_POWER_SUB_DOMAIN_SADC      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_SADC)
#define PM_POWER_SUB_DOMAIN_PWM       (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_PWM)
#define PM_POWER_SUB_DOMAIN_I3C       (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I3C)
#define PM_POWER_SUB_DOMAIN_TIMER2    (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_TIMER2)
#define PM_POWER_SUB_DOMAIN_UART4     (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_UART4)
#define PM_POWER_SUB_DOMAIN_IPI       (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_IPI)
#define PM_POWER_SUB_DOMAIN_XDAC0     (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_XDAC0)
#define PM_POWER_SUB_DOMAIN_XDAC1     (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_XDAC1)
#define PM_POWER_SUB_DOMAIN_DMA0      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_DMA0)
#define PM_POWER_SUB_DOMAIN_MBOX      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_MBOX)
#define PM_POWER_SUB_DOMAIN_CP_HSPL   (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_HSPL)
#define PM_POWER_SUB_DOMAIN_AUD       (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_AUD)
#define PM_POWER_SUB_DOMAIN_SPDIF0    (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_SPDIF0)
#define PM_POWER_SUB_DOMAIN_SPDIF1    (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_SPDIF1)
#define PM_POWER_SUB_DOMAIN_I2S0      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2S0)
#define PM_POWER_SUB_DOMAIN_I2S1      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2S1)
#define PM_POWER_SUB_DOMAIN_I2S2      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2S2)
#define PM_POWER_SUB_DOMAIN_I2S3      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2S3)
#define PM_POWER_SUB_DOMAIN_I2S4      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_I2S4)
#define PM_POWER_SUB_DOMAIN_CEC       (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_CEC)
#define PM_POWER_SUB_DOMAIN_CPU1      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_CPU1)
#define PM_POWER_SUB_DOMAIN_PM        (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_PM)
#define PM_POWER_SUB_DOMAIN_NONE      (POWER_SUB_DOMAIN_NAME_CP_CPU1_BAKP_AUDP_NONE)

/* CP: sub domain vehp spi debug */
#define PM_POWER_SUB_DOMAIN_LA        (POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_LA)
#define PM_POWER_SUB_DOMAIN_CAN0      (POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_CAN0)
#define PM_POWER_SUB_DOMAIN_CAN1      (POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_CAN1)
#define PM_POWER_SUB_DOMAIN_SCR0      (POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_SCR0)
#define PM_POWER_SUB_DOMAIN_LIN0      (POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_LIN0)
#define PM_POWER_SUB_DOMAIN_IRDA0     (POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_IRDA0)
#define PM_POWER_SUB_DOMAIN_IRDA1     (POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_IRDA1)
#define PM_POWER_SUB_DOMAIN_IRDA2     (POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_IRDA2)
#define PM_POWER_SUB_DOMAIN_IRDA3     (POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_IRDA3)
#define PM_POWER_SUB_DOMAIN_SPI_DEBUG (POWER_SUB_DOMAIN_NAME_VEHP_SPI_DEBUG_SPI_DEBUG)

/* CP: sub domain wrlp encp */
#define PM_POWER_SUB_DOMAIN_BTDM      (POWER_SUB_DOMAIN_NAME_WRLP_ENCP_BTDM)
#define PM_POWER_SUB_DOMAIN_BK24      (POWER_SUB_DOMAIN_NAME_WRLP_ENCP_BK24)
#define PM_POWER_SUB_DOMAIN_XVR       (POWER_SUB_DOMAIN_NAME_WRLP_ENCP_XVR)
#define PM_POWER_SUB_DOMAIN_MAC       (POWER_SUB_DOMAIN_NAME_WRLP_ENCP_MAC)
#define PM_POWER_SUB_DOMAIN_PHY       (POWER_SUB_DOMAIN_NAME_WRLP_ENCP_PHY)
#define PM_POWER_SUB_DOMAIN_THREAD    (POWER_SUB_DOMAIN_NAME_WRLP_ENCP_THREAD)
#define PM_POWER_SUB_DOMAIN_SHANHAI   (POWER_SUB_DOMAIN_NAME_WRLP_ENCP_SHANHAI)
#define PM_POWER_SUB_DOMAIN_OTP_AHB   (POWER_SUB_DOMAIN_NAME_WRLP_ENCP_OTP_AHB)
#define PM_POWER_SUB_DOMAIN_OTP_APB   (POWER_SUB_DOMAIN_NAME_WRLP_ENCP_OTP_APB)
#define PM_POWER_SUB_DOMAIN_RF        (POWER_SUB_DOMAIN_NAME_WRLP_ENCP_RF)

/* AP: sub domain hsusb power */
#define PM_POWER_SUB_DOMAIN_SYSCFG    (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_SYSCFG)
#define PM_POWER_SUB_DOMAIN_MEMCHK    (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_MEMCHK)
#define PM_POWER_SUB_DOMAIN_QSPI0     (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_QSPI0)
#define PM_POWER_SUB_DOMAIN_QSPI1     (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_QSPI1)
#define PM_POWER_SUB_DOMAIN_SDIO0     (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_SDIO0)
#define PM_POWER_SUB_DOMAIN_SDIO1     (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_SDIO1)
#define PM_POWER_SUB_DOMAIN_PSRAM0    (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_PSRAM0)
#define PM_POWER_SUB_DOMAIN_PSRAM1    (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_PSRAM1)
#define PM_POWER_SUB_DOMAIN_ENET0     (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_ENET0)
#define PM_POWER_SUB_DOMAIN_USB_FS    (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_USB_FS)
#define PM_POWER_SUB_DOMAIN_USB_HS    (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_USB_HS)
#define PM_POWER_SUB_DOMAIN_AP_HSPL   (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_HSPL)
#define PM_POWER_SUB_DOMAIN_PPHS      (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_PPHS)
#define PM_POWER_SUB_DOMAIN_WWDT      (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_WWDT)
#define PM_POWER_SUB_DOMAIN_UART5     (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_UART5)
#define PM_POWER_SUB_DOMAIN_TIMER4    (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_TIMER4)
#define PM_POWER_SUB_DOMAIN_TIMER5    (POWER_SUB_DOMAIN_NAME_HSUSB_POWER_TIMER5)

#define PM_POWER_SUB_DOMAIN_AP_CPU    (POWER_SUB_DOMAIN_NAME_AP_CPU)


#ifdef __cplusplus
}
#endif
