#pragma once

#if CONFIG_SPE
#define GPIO_0_DEFAULT_MAP {GPIO_0,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2C1_SCL,        GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#define GPIO_1_DEFAULT_MAP {GPIO_1,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2C1_SDA,        GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},
#else
#define GPIO_0_DEFAULT_MAP
#define GPIO_1_DEFAULT_MAP
#endif

/*	 gpio_id  second_func_en           second_func_dev         time_sharing_func_dev  pull_mode        int_en            int_type                 low_power_io_ctrl                driver_capacity         gpio_skip */
#define GPIO_DEFAULT_DEV_CONFIG  \
{\
	GPIO_0_DEFAULT_MAP \
	GPIO_1_DEFAULT_MAP \
	{GPIO_2,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO_HOST_CLK,   GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_3,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO_HOST_CMD,   GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_4,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO_HOST_DATA0, GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_5,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_6,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2S0_CLK,        GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_7,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2S0_SYNC,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_8,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_9,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_I2S0_DOUT,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	/* GPIO_12: ADC config pin, output pull-down to prevent ADC internal comparator charge from failing to discharge */\
	{GPIO_12, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID, GPIO_PULL_DOWN_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_13, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_USB0_DN,         GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_14, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_CLK,         GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_15, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_DISP,        GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_16, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_DE,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_17, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_18, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_VSYNC,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_19, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R7,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_20, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R6,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_21, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R5,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_22, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R4,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_23, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R3,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_24, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G7,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_25, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G6,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_26, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G5,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_27, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_MCLK,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_28, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2S0_MCLK,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_29, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PCLK,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_30, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_HSYNC,      GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_31, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_VSYNC,      GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_32, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA0,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_33, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA1,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_34, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA2,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_35, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA3,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_36, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA4,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_37, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA5,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_38, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA6,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_39, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA7,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_40, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G4,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_41, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G3,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_42, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G2,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_43, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B7,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_44, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B6,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_45, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B5,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_46, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B4,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_47, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B3,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_48, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R2,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_49, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R1,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_50, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R0,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_51, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G1,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_52, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G0,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_53, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B2,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_54, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B1,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_55, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B0,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_64, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_UART5_RXD,       GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_65, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_UART5_TXD,       GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
}
