/****************************************************************************
 *  (c) Copyright 2007 Wi-Fi Alliance.  All Rights Reserved
 *
 *
 *  LICENSE
 *
 *  License is granted only to Wi-Fi Alliance members and designated
 *  contractors (“Authorized Licensees”).  Authorized Licensees are granted
 *  the non-exclusive, worldwide, limited right to use, copy, import, export
 *  and distribute this software:
 *  (i) solely for noncommercial applications and solely for testing Wi-Fi
 *  equipment; and
 *  (ii) solely for the purpose of embedding the software into Authorized
 *  Licensee’s proprietary equipment and software products for distribution to
 *  its customers under a license with at least the same restrictions as
 *  contained in this License, including, without limitation, the disclaimer of
 *  warranty and limitation of liability, below.  The distribution rights
 *  granted in clause
 *  (ii), above, include distribution to third party companies who will
 *  redistribute the Authorized Licensee’s product to their customers with or
 *  without such third party’s private label. Other than expressly granted
 *  herein, this License is not transferable or sublicensable, and it does not
 *  extend to and may not be used with non-Wi-Fi applications.  Wi-Fi Alliance
 *  reserves all rights not expressly granted herein. 
 * 
 *  Except as specifically set forth above, commercial derivative works of
 *  this software or applications that use the Wi-Fi scripts generated by this
 *  software are NOT AUTHORIZED without specific prior written permission from
 *  Wi-Fi Alliance.
 * 
 *  Non-Commercial derivative works of this software for internal use are
 *  authorized and are limited by the same restrictions; provided, however,
 *  that the Authorized Licensee shall provide Wi-Fi Alliance with a copy of
 *  such derivative works under a perpetual, payment-free license to use,
 *  modify, and distribute such derivative works for purposes of testing Wi-Fi
 *  equipment.
 * 
 *  Neither the name of the author nor "Wi-Fi Alliance" may be used to endorse
 *  or promote products that are derived from or that use this software without
 *  specific prior written permission from Wi-Fi Alliance.
 *
 *  THIS SOFTWARE IS PROVIDED BY WI-FI ALLIANCE "AS IS" AND ANY EXPRESS OR
 *  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE,
 *  ARE DISCLAIMED. IN NO EVENT SHALL WI-FI ALLIANCE BE LIABLE FOR ANY DIRECT,
 *  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *  (INCLUDING, BUT NOT LIMITED TO, THE COST OF PROCUREMENT OF SUBSTITUTE
 *  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 *  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 *  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE) ARISING IN ANY WAY OUT OF
 *  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. ******************************************************************************
 */
 

/*
 * File: wfa_tlv.h
 *  definitions for each of command types. 
 *  format:
 *  ---------------------------------------------------
 *  |  tag   | length |   value   
 *  --------------------------------------------------- 
 *   2 bytes   2bytes    defined by length 
 */
#ifndef _WFA_TLV_H
#define _WFA_TLV_H

#include "wfa_types.h"

#define INTEGER_1 0x0001            /* byte */
#define INTEGER_2 0x0002            /* word */
#define OCTET_STRING 0x0003         /* string */

typedef struct _wfatlvHdr 
{
    WORD tag;   /* tag/type */
    WORD len;   /* value length */
} wfaTLV;

#define WFA_TLV_HDR_LEN sizeof(wfaTLV)

#define WFA_ENC_TLV(the_tag, the_len, the_value, tlv_data)                                \
do{                                                                                       \
    DPRINT_BOX_TLV(" < TLV > WfaEncodeTlv: %s" , #the_tag);                               \
    wfaEncodeTLV(the_tag, the_len, (BYTE *)the_value, tlv_data);                          \
} while(0);

enum cmd_tags {
    /*
    ###################################################################################################
    #                                   GENERIC FUNCTIONS                                             #
    ###################################################################################################
    */
    WFA_GET_VERSION_TLV =                 0x01,
    WFA_TRAFFIC_SEND_PING_TLV,
    WFA_TRAFFIC_STOP_PING_TLV,
    WFA_TRAFFIC_AGENT_CONFIG_TLV,
    WFA_TRAFFIC_AGENT_SEND_TLV,
    WFA_TRAFFIC_AGENT_RECV_START_TLV,
    WFA_TRAFFIC_AGENT_RECV_STOP_TLV,
    WFA_TRAFFIC_AGENT_RESET_TLV,
    WFA_TRAFFIC_AGENT_STATUS_TLV,
    /*
    ###################################################################################################
    #                                   STAUT FUNCTIONS                                               #
    ###################################################################################################
    */
    WFA_STA_GET_IP_CONFIG_TLV,
    WFA_STA_SET_IP_CONFIG_TLV,
    WFA_STA_GET_MAC_ADDRESS_TLV,
    WFA_STA_SET_MAC_ADDRESS_TLV,
    WFA_STA_IS_CONNECTED_TLV,
    WFA_STA_VERIFY_IP_CONNECTION_TLV,
    WFA_STA_GET_BSSID_TLV,
    WFA_STA_GET_STATS_TLV,
    WFA_STA_SET_ENCRYPTION_TLV,
    WFA_STA_SET_PSK_TLV,
    WFA_STA_SET_EAPTLS_TLV,
    WFA_STA_SET_UAPSD_TLV,
    WFA_STA_ASSOCIATE_TLV,
    WFA_STA_SET_EAPTTLS_TLV,
    WFA_STA_SET_EAPSIM_TLV,
    WFA_STA_SET_PEAP_TLV,
    WFA_STA_SET_IBSS_TLV,
    WFA_STA_GET_INFO_TLV,
    WFA_DEVICE_GET_INFO_TLV,
    WFA_DEVICE_LIST_IF_TLV,
    WFA_STA_DEBUG_SET_TLV,
    WFA_STA_SET_MODE_TLV,
    WFA_STA_UPLOAD_TLV,
    WFA_STA_SET_WMM_TLV,
    WFA_STA_REASSOCIATE_TLV,
    WFA_STA_SET_PWRSAVE_TLV,
    WFA_STA_SEND_NEIGREQ_TLV,
    WFA_STA_PRESET_PARAMETERS_TLV,
    WFA_STA_SET_EAPFAST_TLV,
    WFA_STA_SET_EAPAKA_TLV,
    WFA_STA_SET_EAPAKAPRIME_TLV,
    WFA_STA_SET_SYSTIME_TLV,
    WFA_STA_SET_11N_TLV,
    WFA_STA_SET_WIRELESS_TLV,
    WFA_STA_SEND_ADDBA_TLV,
    WFA_STA_SEND_COEXIST_MGMT_TLV,
    WFA_STA_SET_RIFS_TEST_TLV,
    WFA_STA_RESET_DEFAULT_TLV,
    WFA_STA_DISCONNECT_TLV,
    WFA_STA_DEV_SEND_FRAME_TLV,
    WFA_STA_SET_SECURITY_TLV,
    WFA_STA_SET_RADIO_TLV,
    WFA_STA_SET_RFEATURE_TLV,
    WFA_STA_SENDTCP_TLV,
    WFA_STA_RCVTCP_TLV,
    WFA_STA_READ_TCP_TLV,
    WFA_STA_STOP_IPERF_TLV,
    WFA_STA_SCAN_TLV,
	WFA_STA_SET_POWER_SAVE_TLV,
    /*
    ###################################################################################################
    #                                     P2P FUNCTIONS                                               #
###################################################################################################
    */
    WFA_STA_P2P_GET_DEV_ADDRESS_TLV,
    WFA_STA_P2P_SETP2P_TLV,
    WFA_STA_P2P_CONNECT_TLV,
    WFA_STA_P2P_START_AUTO_GO_TLV,
    WFA_STA_P2P_START_GRP_FORMATION_TLV,
    WFA_STA_P2P_DISSOLVE_TLV,
    WFA_STA_P2P_SEND_INV_REQ_TLV,
    WFA_STA_P2P_ACCEPT_INV_REQ_TLV,
    WFA_STA_P2P_SEND_PROV_DIS_REQ_TLV,
    WFA_STA_WPS_SETWPS_PBC_TLV,
    WFA_STA_WPS_READ_PIN_TLV,
    WFA_STA_WPS_ENTER_PIN_TLV,
    WFA_STA_P2P_GET_PSK_TLV,
    WFA_STA_P2P_RESET_TLV,
    WFA_STA_WPS_READ_LABEL_TLV,
    WFA_STA_P2P_GET_IP_CONFIG_TLV,
    WFA_STA_P2P_SEND_SERVICE_DISCOVERY_REQ_TLV,
    WFA_STA_P2P_SEND_PRESENCE_REQ_TLV,
    WFA_STA_P2P_SET_SLEEP_TLV,
    WFA_STA_P2P_SET_OPPORTUNISTIC_PS_TLV,
    WFA_STA_P2P_ADD_ARP_TABLE_ENTRY_TLV,
    WFA_STA_P2P_BLOCK_ICMP_RESPONSE_TLV,
    /*
    ###################################################################################################
    #                                    APUT FUNCTIONS                                               #
    ###################################################################################################
    */
    WFA_AP_SET_WIRELESS_TLV,
    WFA_AP_SET_SECURITY_TLV,
    WFA_AP_SET_APQOS_TLV,
    WFA_AP_SET_STAQOS_TLV,
    WFA_AP_SET_11N_WIRELESS_TLV,
    WFA_AP_GET_WIRELESS_TLV,
    WFA_AP_GET_APQOS_TLV,
    WFA_AP_SET_RADIUS_TLV,
    WFA_AP_CA_VERSION_TLV,
    WFA_AP_RESET_DEFAULT_TLV,
    WFA_AP_REBOOT_TLV,
    WFA_AP_CONFIG_COMMIT_TLV,
    WFA_AP_GET_INFO_TLV,
    WFA_AP_DEAUTH_STA_TLV,
    WFA_AP_ADD_NEWIF_TLV,
    WFA_AP_SET_PMF_TLV,
    WFA_AP_GET_MAC_ADDRESS_TLV,
    WFA_AP_SET_11D_TLV,
    WFA_AP_SET_11H_TLV,
    WFA_AP_SET_RFEATURE_TLV,
    /*
    ###################################################################################################
    #                                     WFD FUNCTIONS                                               #
    ###################################################################################################
    */
    WFA_STA_START_WFD_CONNECTION_TLV,
    WFA_STA_CLI_CMD_TLV,
    WFA_STA_CONNECT_GO_START_WFD_TLV,
    WFA_STA_GENERATE_EVENT_TLV,
    WFA_STA_REINVOKE_WFD_SESSION_TLV,
    WFA_STA_GET_PARAMETER_TLV,
    WFA_STA_COMMANDS_END,

    WFA_INVALID_TLV = 0xFFFF
};

#define WFA_TLV_HEAD_LEN 1+2

extern WORD wfaGetTag(BYTE *tlv_data);
extern void wfaSetTag(BYTE *tlv_data, BYTE new_tag);
extern WORD wfaGetTLVLen(BYTE *tlv_data);
extern WORD wfaGetValueLen(BYTE *tlv_data);
extern void wfaAliasByTag(BYTE the_tag, char *aliasStr);
extern int wfaDecodeTLV(BYTE *tlv_data, int tlv_len, WORD *ptlv_tag, int *ptlv_val_len, BYTE *ptlv_value);
extern int wfaEncodeTLV(WORD the_tag, WORD the_len, BYTE *the_value, BYTE *tlv_data);

extern WORD wfaGetValueType(BYTE the_tag, BYTE *tlv_data);

#endif
