/****************************************************************************
 *  (c) Copyright 2007 Wi-Fi Alliance.  All Rights Reserved
 *
 *
 *  LICENSE
 *
 *  License is granted only to Wi-Fi Alliance members and designated
 *  contractors (“Authorized Licensees”).  Authorized Licensees are granted
 *  the non-exclusive, worldwide, limited right to use, copy, import, export
 *  and distribute this software:
 *  (i) solely for noncommercial applications and solely for testing Wi-Fi
 *  equipment; and
 *  (ii) solely for the purpose of embedding the software into Authorized
 *  Licensee’s proprietary equipment and software products for distribution to
 *  its customers under a license with at least the same restrictions as
 *  contained in this License, including, without limitation, the disclaimer of
 *  warranty and limitation of liability, below.  The distribution rights
 *  granted in clause
 *  (ii), above, include distribution to third party companies who will
 *  redistribute the Authorized Licensee’s product to their customers with or
 *  without such third party’s private label. Other than expressly granted
 *  herein, this License is not transferable or sublicensable, and it does not
 *  extend to and may not be used with non-Wi-Fi applications.  Wi-Fi Alliance
 *  reserves all rights not expressly granted herein. 
 * 
 *  Except as specifically set forth above, commercial derivative works of
 *  this software or applications that use the Wi-Fi scripts generated by this
 *  software are NOT AUTHORIZED without specific prior written permission from
 *  Wi-Fi Alliance.
 * 
 *  Non-Commercial derivative works of this software for internal use are
 *  authorized and are limited by the same restrictions; provided, however,
 *  that the Authorized Licensee shall provide Wi-Fi Alliance with a copy of
 *  such derivative works under a perpetual, payment-free license to use,
 *  modify, and distribute such derivative works for purposes of testing Wi-Fi
 *  equipment.
 * 
 *  Neither the name of the author nor "Wi-Fi Alliance" may be used to endorse
 *  or promote products that are derived from or that use this software without
 *  specific prior written permission from Wi-Fi Alliance.
 *
 *  THIS SOFTWARE IS PROVIDED BY WI-FI ALLIANCE "AS IS" AND ANY EXPRESS OR
 *  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE,
 *  ARE DISCLAIMED. IN NO EVENT SHALL WI-FI ALLIANCE BE LIABLE FOR ANY DIRECT,
 *  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *  (INCLUDING, BUT NOT LIMITED TO, THE COST OF PROCUREMENT OF SUBSTITUTE
 *  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 *  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 *  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE) ARISING IN ANY WAY OUT OF
 *  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. ******************************************************************************
 */
 

#ifndef _WFA_DUT_PARAM_H
#define _WFA_DUT_PARAM_H

#define GENERATE_SETUP_ENUM(ENUM) DUT_SETUP_##ENUM,
#define GENERATE_FEATS_ENUM(ENUM) DUT_FEATS_##ENUM,
#define GENERATE_COMMON_ENUM(ENUM) DUT_COMMON_##ENUM,
#define GENERATE_SMAC_ENUM(ENUM) DUT_SMAC_##ENUM,
#define GENERATE_FMAC_ENUM(ENUM) DUT_FMAC_##ENUM,

// SETUP PARAMS
#define FOREACH_DUT_SETUP_PARAM(PARAM)                                                   \
        PARAM(platform)                                                                  \
        PARAM(platform_id)                                                               \
        PARAM(clock)                                                                     \
        PARAM(bridge)                                                                    \
        PARAM(radio)                                                                     \
        PARAM(ip_index)                                                                  \
        PARAM(umac)                                                                      \
        PARAM(mactrace)                                                                  \
        PARAM(setdata)                                                                  \
        PARAM(debug)

// SPECIFIC FEATURES
#define FOREACH_DUT_FEATS_PARAM(PARAM)                                                   \
        PARAM(width)                                                                     \
        PARAM(11hap)                                                                     \
        PARAM(11dap)                                                                     \
        PARAM(dtim)                                                                      \
        PARAM(obss_scan)                                                                 \
        PARAM(wpa_group_rekey)                                                           \
        PARAM(wpa_strict_rekey)                                                          \
        PARAM(gf)                                                                        \
        PARAM(pmf)                                                                       \
        PARAM(p2p)

// MODULE PARAMS
// Common
#define FOREACH_DUT_COMMON_PARAM(PARAM)                                                  \
        PARAM(custregd)                                                                  \
        PARAM(phycfg)                                                                    \
        PARAM(nss)                                                                       \
        PARAM(amsdu_maxnb)                                                               \
        PARAM(amsdu_rx_max)                                                              \
        PARAM(ap_uapsd_on)                                                               \
        PARAM(bfmee)                                                                     \
        PARAM(bfmer)                                                                     \
        PARAM(ht_on)                                                                     \
        PARAM(ldpc_on)                                                                   \
        PARAM(mcs_map)                                                                   \
		PARAM(he_mcs_map)                                                                \
        PARAM(mesh)                                                                      \
        PARAM(murx)                                                                      \
        PARAM(mutx)                                                                      \
        PARAM(mutx_on)                                                                   \
        PARAM(ps_on)                                                                     \
        PARAM(dpsm)                                                                      \
        PARAM(sgi)                                                                       \
        PARAM(sgi80)                                                                     \
        PARAM(tdls)                                                                      \
        PARAM(uapsd_queues)                                                              \
        PARAM(uapsd_timeout)                                                             \
        PARAM(use_2040)                                                                  \
        PARAM(use_80)                                                                    \
        PARAM(vht_on)                                                                    \
        PARAM(stbc_on)                                                                   \
        PARAM(he_ul_on)                                                                  \
        PARAM(he_on)                                                                     \
        PARAM(lp_clk_ppm)                                                                \
        PARAM(tx_lft)                                                                    \
        PARAM(tx_to_bk)                                                                  \
        PARAM(tx_to_be)                                                                  \
        PARAM(tx_to_vi)                                                                  \
        PARAM(tx_to_vo)

// SMAC SPECIFIC
#define FOREACH_DUT_SMAC_PARAM(PARAM)                                                    \
        PARAM(amsdu_force)                                                               \
        PARAM(agg_tx)

// FMAC SPECIFIC
#define FOREACH_DUT_FMAC_PARAM(PARAM)                                                    \
        PARAM(ant_div)

enum dut_setup_param
{
    FOREACH_DUT_SETUP_PARAM(GENERATE_SETUP_ENUM)
    DUT_SETUP_PARAM_MAX
};

 enum dut_feats_param
 {
     FOREACH_DUT_FEATS_PARAM(GENERATE_FEATS_ENUM)
     DUT_FEATS_PARAM_MAX
 };

enum dut_common_param
{
    FOREACH_DUT_COMMON_PARAM(GENERATE_COMMON_ENUM)
    DUT_COMMON_PARAM_MAX
};

enum dut_smac_param
{
    FOREACH_DUT_SMAC_PARAM(GENERATE_SMAC_ENUM)
    DUT_SMAC_PARAM_MAX
};

enum dut_fmac_param
{
    FOREACH_DUT_FMAC_PARAM(GENERATE_FMAC_ENUM)
    DUT_FMAC_PARAM_MAX
};

extern const char *dut_setup_param_name[];

extern int dut_setup_param_default[];

extern int dut_setup_param[];

extern const char *dut_feats_param_name[];

extern int dut_feats_param_default[];

extern int dut_feats_param[];

extern const char *dut_common_param_name[];

extern int dut_common_param_default[];

extern int dut_common_param[];

extern const char *dut_smac_param_name[];

extern int dut_smac_param_default[];

extern int dut_smac_param[];

extern const char *dut_fmac_param_name[];

extern int dut_fmac_param_default[];

extern int dut_fmac_param[];

int wfa_dut_param_get_default(void);
int wfa_dut_param_set_default(void);
int wfa_dut_param_build_options(char *buf, int buflen);

#define PARAM_SETUP(param)  dut_setup_param[DUT_SETUP_##param]
#define PARAM_SETUP_DEF(param)  dut_setup_param_default[DUT_SETUP_##param]
#define PARAM_FEATS(param)  dut_feats_param[DUT_FEATS_##param]
#define PARAM_FEATS_DEF(param)  dut_feats_param_default[DUT_FEATS_##param]
#define PARAM_COMMON(param)  dut_common_param[DUT_COMMON_##param]
#define PARAM_COMMON_DEF(param)  dut_common_param_default[DUT_COMMON_##param]
#define PARAM_SMAC(param)  dut_smac_param[DUT_SMAC_##param]
#define PARAM_SMAC_DEF(param)  dut_smac_param_default[DUT_SMAC_##param]
#define PARAM_FMAC(param)  dut_fmac_param[DUT_FMAC_##param]
#define PARAM_FMAC_DEF(param)  dut_fmac_param_default[DUT_FMAC_##param]

enum
{
    DUT_TYPE_SMAC,
    DUT_TYPE_FMAC,
    DUT_TYPE_FHOST
};

enum
{
    DINIV6 = 6,
    CEVAV7 = 7,
};

#define DUT_TYPE     PARAM_SETUP(umac)
#define DUT_WIDTH    PARAM_FEATS(width)
#define DUT_PLATFORM PARAM_SETUP(platform)
#define DUT_IP_IDX   PARAM_SETUP(ip_index)

#endif
