set(CSI_CAMERA_DEVICE_FILES "")
set(CSI_CAMERA_PATH src/csi)

if (CONFIG_CSI_CAMERA)
	if (CONFIG_CSI_F58)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_f58.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "f58_detect")
	endif()

	if (CONFIG_CSI_GC2053)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_gc2053.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "gc2053_detect")
	endif()

	if (CONFIG_CSI_GC20C3)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_gc20c3.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "gc20C3_detect")
	endif()

	if (CONFIG_CSI_CV2005)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_cv2005.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "cv2005_detect")
	endif()

	if (CONFIG_CSI_CV2002)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_cv2002.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "cv2002_detect")
	endif()

	if (CONFIG_CSI_CV2008)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_cv2008.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "cv2008_detect")
	endif()

	if (CONFIG_CSI_GC4653)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_gc4653.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "gc4653_detect")
	endif()

	if (CONFIG_CSI_OV2775)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_ov2775.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "ov2775_detect")
	endif()

	if (CONFIG_CSI_SC4336)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_sc4336.c)
		list(APPEND CSI_CAMERA_FUNCTION_SYMBOLS "sc4336_detect")
	endif()

	if (CONFIG_CSI_SC3336)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_sc3336.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "sc3336_detect")
	endif()

	if (CONFIG_CSI_SC3336P)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_sc3336p.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "sc3336p_detect")
	endif()

	if (CONFIG_CSI_MIPI_BRIDGE)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_mipi_bridge.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "mipi_bridge_detect")
	endif()

	if (CONFIG_CSI_TP2863)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_tp2863.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "tp2863_detect")
	endif()
endif()


