// Copyright 2022-2023 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once


#ifdef __cplusplus
extern "C" {
#endif


#define AON_PMU_R0_ADDR (SOC_AON_PMU_REG_BASE + (0x0 << 2))

#define AON_PMU_R0_MEMCHK_BPS_POS (0)
#define AON_PMU_R0_MEMCHK_BPS_MASK (0x1)

#define AON_PMU_R0_FAST_BOOT_POS (1)
#define AON_PMU_R0_FAST_BOOT_MASK (0x1)

#define AON_PMU_R0_RESERVED_BIT_2_3_POS (2)
#define AON_PMU_R0_RESERVED_BIT_2_3_MASK (0x3)

#define AON_PMU_R0_FLASH_REMAP_SEL_POS (4)
#define AON_PMU_R0_FLASH_REMAP_SEL_MASK (0x1)

#define AON_PMU_R0_AON_REG0_FOR_SOFTWARE_POS (5)
#define AON_PMU_R0_AON_REG0_FOR_SOFTWARE_MASK (0x7)

#define AON_PMU_R0_GPIO_SLEEP_POS (31)
#define AON_PMU_R0_GPIO_SLEEP_MASK (0x1)

#define AON_PMU_R2_ADDR (SOC_AON_PMU_REG_BASE + (0x2 << 2))

#define AON_PMU_R2_WDT_RST_ANA_POS (0)
#define AON_PMU_R2_WDT_RST_ANA_MASK (0x1)

#define AON_PMU_R2_WDT_RST_TOP_POS (1)
#define AON_PMU_R2_WDT_RST_TOP_MASK (0x1)

#define AON_PMU_R2_WDT_RST_AON_POS (2)
#define AON_PMU_R2_WDT_RST_AON_MASK (0x1)

#define AON_PMU_R2_WDT_RST_AWT_POS (3)
#define AON_PMU_R2_WDT_RST_AWT_MASK (0x1)

#define AON_PMU_R2_WDT_RST_GPIO_POS (4)
#define AON_PMU_R2_WDT_RST_GPIO_MASK (0x1)

#define AON_PMU_R2_WDT_RST_RTC_POS (5)
#define AON_PMU_R2_WDT_RST_RTC_MASK (0x1)

#define AON_PMU_R2_WDT_RST_WDT_POS (6)
#define AON_PMU_R2_WDT_RST_WDT_MASK (0x1)

#define AON_PMU_R2_WDT_RST_PMU_POS (7)
#define AON_PMU_R2_WDT_RST_PMU_MASK (0x1)

#define AON_PMU_R2_WDT_RST_BLP_WLP_POS (8)
#define AON_PMU_R2_WDT_RST_BLP_WLP_MASK (0x1)

#define AON_PMU_R2_RESERVED_BIT_9_15_POS (9)
#define AON_PMU_R2_RESERVED_BIT_9_15_MASK (0x7f)

#define AON_PMU_R2_M55_ISO_EN_POS (16)
#define AON_PMU_R2_M55_ISO_EN_MASK (0x1)

#define AON_PMU_R2_M55_RSTN_POS (17)
#define AON_PMU_R2_M55_RSTN_MASK (0x1)

#define AON_PMU_R2_M55_MEM_RET_POS (18)
#define AON_PMU_R2_M55_MEM_RET_MASK (0x1)

#define AON_PMU_R2_M55_MEM3_PWD_POS (19)
#define AON_PMU_R2_M55_MEM3_PWD_MASK (0x1)

#define AON_PMU_R2_M55_CLK_EN_POS (20)
#define AON_PMU_R2_M55_CLK_EN_MASK (0x1)

#define AON_PMU_R2_M55_MEM4_PWD_POS (21)
#define AON_PMU_R2_M55_MEM4_PWD_MASK (0x1)

#define AON_PMU_R2_M55_MEM5_PWD_POS (22)
#define AON_PMU_R2_M55_MEM5_PWD_MASK (0x1)

#define AON_PMU_R2_M55_MEM6_PWD_POS (23)
#define AON_PMU_R2_M55_MEM6_PWD_MASK (0x1)

#define AON_PMU_R2_M55_CPU2_CACHE_PWD_POS (24)
#define AON_PMU_R2_M55_CPU2_CACHE_PWD_MASK (0x1)

#define AON_PMU_R2_M55_CPU3_CACHE_PWD_POS (25)
#define AON_PMU_R2_M55_CPU3_CACHE_PWD_MASK (0x1)

#define AON_PMU_R2_M55_CPU2_CACHE_INIT_DIS_MAINT_POS (26)
#define AON_PMU_R2_M55_CPU2_CACHE_INIT_DIS_MAINT_MASK (0x1)

#define AON_PMU_R2_M55_CPU3_CACHE_INIT_DIS_MAINT_POS (27)
#define AON_PMU_R2_M55_CPU3_CACHE_INIT_DIS_MAINT_MASK (0x1)

#define AON_PMU_R2_M55_MEM_AUTO_SET_POS (28)
#define AON_PMU_R2_M55_MEM_AUTO_SET_MASK (0x1)

#define AON_PMU_R2_M55_AUTO_SEL_POS (29)
#define AON_PMU_R2_M55_AUTO_SEL_MASK (0x1)

#define AON_PMU_R2_RESERVED_BIT_30_30_POS (30)
#define AON_PMU_R2_RESERVED_BIT_30_30_MASK (0x1)

#define AON_PMU_R2_OTP_VDD_EN_POS (31)
#define AON_PMU_R2_OTP_VDD_EN_MASK (0x1)

#define AON_PMU_R3_ADDR (SOC_AON_PMU_REG_BASE + (0x3 << 2))

#define AON_PMU_R3_FOR_SW_POS (0)
#define AON_PMU_R3_FOR_SW_MASK (0x7fffffff)

#define AON_PMU_R3_SHUTDOWN_FLAG_POS (31)
#define AON_PMU_R3_SHUTDOWN_FLAG_MASK (0x1)

#define AON_PMU_R4_ADDR (SOC_AON_PMU_REG_BASE + (0x4 << 2))

#define AON_PMU_R4_PROGRAM_STATE_POS (0)
#define AON_PMU_R4_PROGRAM_STATE_MASK (0xf)

#define AON_PMU_R4_RESERVED_BIT_4_30_POS (4)
#define AON_PMU_R4_RESERVED_BIT_4_30_MASK (0x7ffffff)

#define AON_PMU_R4_AON_ENCP_JTAG_DIABLE_POS (31)
#define AON_PMU_R4_AON_ENCP_JTAG_DIABLE_MASK (0x1)

#define AON_PMU_R5_ADDR (SOC_AON_PMU_REG_BASE + (0x5 << 2))

#define AON_PMU_R5_ENCP_SPI_TO_AHB_ENABLE_POS (0)
#define AON_PMU_R5_ENCP_SPI_TO_AHB_ENABLE_MASK (0x1)

#define AON_PMU_R5_RESERVED_BIT_1_31_POS (1)
#define AON_PMU_R5_RESERVED_BIT_1_31_MASK (0x7fffffff)

#define AON_PMU_R25_ADDR (SOC_AON_PMU_REG_BASE + (0x25 << 2))

#define AON_PMU_R25_REG3V_CLK_POS (0)
#define AON_PMU_R25_REG3V_CLK_MASK (0xffffffff)

#define AON_PMU_R40_ADDR (SOC_AON_PMU_REG_BASE + (0x40 << 2))

#define AON_PMU_R40_WAKE1_DELAY_POS (0)
#define AON_PMU_R40_WAKE1_DELAY_MASK (0xf)

#define AON_PMU_R40_WAKE2_DELAY_POS (4)
#define AON_PMU_R40_WAKE2_DELAY_MASK (0xf)

#define AON_PMU_R40_WAKE3_DELAY_POS (8)
#define AON_PMU_R40_WAKE3_DELAY_MASK (0xf)

#define AON_PMU_R40_HALT1_DELAY_POS (12)
#define AON_PMU_R40_HALT1_DELAY_MASK (0xf)

#define AON_PMU_R40_HALT2_DELAY_POS (16)
#define AON_PMU_R40_HALT2_DELAY_MASK (0xf)

#define AON_PMU_R40_HALT3_DELAY_POS (20)
#define AON_PMU_R40_HALT3_DELAY_MASK (0xf)

#define AON_PMU_R40_HALT_VOLT_POS (24)
#define AON_PMU_R40_HALT_VOLT_MASK (0x1)

#define AON_PMU_R40_HALT_XTAL_POS (25)
#define AON_PMU_R40_HALT_XTAL_MASK (0x1)

#define AON_PMU_R40_HALT_CORE_POS (26)
#define AON_PMU_R40_HALT_CORE_MASK (0x1)

#define AON_PMU_R40_HALT_FLASH_POS (27)
#define AON_PMU_R40_HALT_FLASH_MASK (0x1)

#define AON_PMU_R40_HALT_ROSC_POS (28)
#define AON_PMU_R40_HALT_ROSC_MASK (0x1)

#define AON_PMU_R40_HALT_RESTEN_POS (29)
#define AON_PMU_R40_HALT_RESTEN_MASK (0x1)

#define AON_PMU_R40_HALT_ISOLAT_POS (30)
#define AON_PMU_R40_HALT_ISOLAT_MASK (0x1)

#define AON_PMU_R40_HALT_CLKENA_POS (31)
#define AON_PMU_R40_HALT_CLKENA_MASK (0x1)

#define AON_PMU_R41_ADDR (SOC_AON_PMU_REG_BASE + (0x41 << 2))

#define AON_PMU_R41_LPO_CONFIG_POS (0)
#define AON_PMU_R41_LPO_CONFIG_MASK (0x3)

#define AON_PMU_R41_FLSHSCK_IOCAP_POS (2)
#define AON_PMU_R41_FLSHSCK_IOCAP_MASK (0x3)

#define AON_PMU_R41_WAKEUP_ENA_POS (4)
#define AON_PMU_R41_WAKEUP_ENA_MASK (0x7f)

#define AON_PMU_R41_GPIO_INT_CLKSEL_POS (11)
#define AON_PMU_R41_GPIO_INT_CLKSEL_MASK (0x1)

#define AON_PMU_R41_RESERVED_BIT_12_13_POS (12)
#define AON_PMU_R41_RESERVED_BIT_12_13_MASK (0x3)

#define AON_PMU_R41_XTAL_SEL_POS (14)
#define AON_PMU_R41_XTAL_SEL_MASK (0x1)

#define AON_PMU_R41_GPIO_FUNC_CTRL_EN_POS (15)
#define AON_PMU_R41_GPIO_FUNC_CTRL_EN_MASK (0x1)

#define AON_PMU_R41_SLEEP_WDT_DISABLE_POS (16)
#define AON_PMU_R41_SLEEP_WDT_DISABLE_MASK (0x1)

#define AON_PMU_R41_RESERVED_BIT_17_18_POS (17)
#define AON_PMU_R41_RESERVED_BIT_17_18_MASK (0x3)

#define AON_PMU_R41_WLP_SWITCH_EN_POS (19)
#define AON_PMU_R41_WLP_SWITCH_EN_MASK (0x1)

#define AON_PMU_R41_LCD_CLK_INV_POS (20)
#define AON_PMU_R41_LCD_CLK_INV_MASK (0x1)

#define AON_PMU_R41_RESERVED_BIT_21_23_POS (21)
#define AON_PMU_R41_RESERVED_BIT_21_23_MASK (0x7)

#define AON_PMU_R41_HALT_LPO_POS (24)
#define AON_PMU_R41_HALT_LPO_MASK (0x1)

#define AON_PMU_R41_HALT_SRAM0_POS (25)
#define AON_PMU_R41_HALT_SRAM0_MASK (0x1)

#define AON_PMU_R41_HALT_SRAM1_POS (26)
#define AON_PMU_R41_HALT_SRAM1_MASK (0x1)

#define AON_PMU_R41_HALT_SRAM2_POS (27)
#define AON_PMU_R41_HALT_SRAM2_MASK (0x1)

#define AON_PMU_R41_MEM_RET_EN_POS (28)
#define AON_PMU_R41_MEM_RET_EN_MASK (0x1)

#define AON_PMU_R41_HALT_CACHE_POS (29)
#define AON_PMU_R41_HALT_CACHE_MASK (0x1)

#define AON_PMU_R41_M52_L2_DIS_CACHE_INIT_DIS_MAINT_POS (30)
#define AON_PMU_R41_M52_L2_DIS_CACHE_INIT_DIS_MAINT_MASK (0x1)

#define AON_PMU_R41_M52_CPU_L2_DIS_CACHE_EN_MAINT_POS (31)
#define AON_PMU_R41_M52_CPU_L2_DIS_CACHE_EN_MAINT_MASK (0x1)

#define AON_PMU_R42_ADDR (SOC_AON_PMU_REG_BASE + (0x42 << 2))

#define AON_PMU_R42_PWD_BLPPWD_POS (0)
#define AON_PMU_R42_PWD_BLPPWD_MASK (0x1)

#define AON_PMU_R42_PWD_WLPPWD_POS (1)
#define AON_PMU_R42_PWD_WLPPWD_MASK (0x1)

#define AON_PMU_R42_BLP_ISOLATE_STATE_POS (2)
#define AON_PMU_R42_BLP_ISOLATE_STATE_MASK (0x1)

#define AON_PMU_R42_WLP_ISOLATE_STATE_POS (3)
#define AON_PMU_R42_WLP_ISOLATE_STATE_MASK (0x1)

#define AON_PMU_R42_RESERVED_BIT_4_31_POS (4)
#define AON_PMU_R42_RESERVED_BIT_4_31_MASK (0xfffffff)

#define AON_PMU_R43_ADDR (SOC_AON_PMU_REG_BASE + (0x43 << 2))

#define AON_PMU_R43_CLR_INT_TOUCHED_POS (0)
#define AON_PMU_R43_CLR_INT_TOUCHED_MASK (0xffff)

#define AON_PMU_R43_CLR_INT_USBPLUG_POS (16)
#define AON_PMU_R43_CLR_INT_USBPLUG_MASK (0x1)

#define AON_PMU_R43_CLR_WAKEUP_POS (17)
#define AON_PMU_R43_CLR_WAKEUP_MASK (0x1)

#define AON_PMU_R43_RESERVED_BIT_18_31_POS (18)
#define AON_PMU_R43_RESERVED_BIT_18_31_MASK (0x3fff)

#define AON_PMU_R70_ADDR (SOC_AON_PMU_REG_BASE + (0x70 << 2))

#define AON_PMU_R70_INT_TOUCHED_POS (0)
#define AON_PMU_R70_INT_TOUCHED_MASK (0xffff)

#define AON_PMU_R70_INT_USBPLUG_POS (16)
#define AON_PMU_R70_INT_USBPLUG_MASK (0x1)

#define AON_PMU_R70_RESERVED_BIT_17_31_POS (17)
#define AON_PMU_R70_RESERVED_BIT_17_31_MASK (0x7fff)

#define AON_PMU_R71_ADDR (SOC_AON_PMU_REG_BASE + (0x71 << 2))

#define AON_PMU_R71_TOUCH_STATE_POS (0)
#define AON_PMU_R71_TOUCH_STATE_MASK (0xffff)

#define AON_PMU_R71_USBPLUG_STATE_POS (16)
#define AON_PMU_R71_USBPLUG_STATE_MASK (0x1)

#define AON_PMU_R71_RESERVED_BIT_17_19_POS (17)
#define AON_PMU_R71_RESERVED_BIT_17_19_MASK (0x7)

#define AON_PMU_R71_WAKEUP_SOURCE_POS (20)
#define AON_PMU_R71_WAKEUP_SOURCE_MASK (0x7f)

#define AON_PMU_R71_RESERVED_BIT_27_31_POS (27)
#define AON_PMU_R71_RESERVED_BIT_27_31_MASK (0x1f)

#define AON_PMU_R74_ADDR (SOC_AON_PMU_REG_BASE + (0x74 << 2))

#define AON_PMU_R74_POR_COREHS_N_POS (0)
#define AON_PMU_R74_POR_COREHS_N_MASK (0x1)

#define AON_PMU_R74_RESERVED_BIT_1_31_POS (1)
#define AON_PMU_R74_RESERVED_BIT_1_31_MASK (0x7fffffff)

#define AON_PMU_R75_ADDR (SOC_AON_PMU_REG_BASE + (0x75 << 2))

#define AON_PMU_R75_ANA_STA4_POS (0)
#define AON_PMU_R75_ANA_STA4_MASK (0xffffffff)

#define AON_PMU_R78_ADDR (SOC_AON_PMU_REG_BASE + (0x78 << 2))

#define AON_PMU_R78_ANA_RTC_STATE_POS (0)
#define AON_PMU_R78_ANA_RTC_STATE_MASK (0xf)

#define AON_PMU_R78_RESERVED_BIT_4_31_POS (4)
#define AON_PMU_R78_RESERVED_BIT_4_31_MASK (0xfffffff)

#define AON_PMU_R79_ADDR (SOC_AON_PMU_REG_BASE + (0x79 << 2))

#define AON_PMU_R79_ANA_RTC_VALUE_POS (0)
#define AON_PMU_R79_ANA_RTC_VALUE_MASK (0xffffffff)

#define AON_PMU_R7A_ADDR (SOC_AON_PMU_REG_BASE + (0x7a << 2))

#define AON_PMU_R7A_AON_MIX0_POS (0)
#define AON_PMU_R7A_AON_MIX0_MASK (0xffffffff)

#define AON_PMU_R7B_ADDR (SOC_AON_PMU_REG_BASE + (0x7b << 2))

#define AON_PMU_R7B_AON3V_REGDI_POS (0)
#define AON_PMU_R7B_AON3V_REGDI_MASK (0xffffffff)

#define AON_PMU_R7C_ADDR (SOC_AON_PMU_REG_BASE + (0x7c << 2))

#define AON_PMU_R7C_ID_POS (0)
#define AON_PMU_R7C_ID_MASK (0xffffffff)

#define AON_PMU_R7D_ADDR (SOC_AON_PMU_REG_BASE + (0x7d << 2))

#define AON_PMU_R7D_LCAL_POS (0)
#define AON_PMU_R7D_LCAL_MASK (0xff)

#define AON_PMU_R7D_L_POS (8)
#define AON_PMU_R7D_L_MASK (0x1)

#define AON_PMU_R7D_ADC_CAL_POS (9)
#define AON_PMU_R7D_ADC_CAL_MASK (0x3f)

#define AON_PMU_R7D_BGCAL_POS (15)
#define AON_PMU_R7D_BGCAL_MASK (0x3f)

#define AON_PMU_R7D_SIG_26MPLL_UNLOCK_POS (21)
#define AON_PMU_R7D_SIG_26MPLL_UNLOCK_MASK (0x1)

#define AON_PMU_R7D_DPLL_UNLOCK_POS (22)
#define AON_PMU_R7D_DPLL_UNLOCK_MASK (0x1)

#define AON_PMU_R7D_H_POS (23)
#define AON_PMU_R7D_H_MASK (0x1ff)

#define AON_PMU_R7E_ADDR (SOC_AON_PMU_REG_BASE + (0x7e << 2))

#define AON_PMU_R7E_CBCAL_POS (0)
#define AON_PMU_R7E_CBCAL_MASK (0x1f)

#define AON_PMU_R7E_AD_STATE_POS (5)
#define AON_PMU_R7E_AD_STATE_MASK (0xf)

#define AON_PMU_R7E_TD_STATES1_POS (9)
#define AON_PMU_R7E_TD_STATES1_MASK (0x1fff)

#define AON_PMU_R7E_H_POS (22)
#define AON_PMU_R7E_H_MASK (0x3ff)

#define AON_PMU_R7F_ADDR (SOC_AON_PMU_REG_BASE + (0x7f << 2))

#define AON_PMU_R7F_TD_STATES2_POS (0)
#define AON_PMU_R7F_TD_STATES2_MASK (0xffffffff)

#ifdef __cplusplus
}
#endif
