# HW platform
platform=7
# softap parameter: set mac address
platform_id=6

# FMAC
umac=1
clock=110
radio=2

# Bandwith: 20,40,80
width=20

# IP address: the last octet
ip_index=76
mactrace=1

# set mac/phy/rf registers
setdata=1

# add wlp4s0 to bridge
bridge=0

# wpa_supplicant add -dd parameter
debug=1

# GreenField
gf=0
pmf=1
p2p=0

# softap paramters
11hap=0
11dap=0
dtim=2
obss_scan=180
wpa_group_rekey=86400
wpa_strict_rekey=0

# Custom regulatory domain
custregd=0

# Use A-MSDU in TX: 0-if advertised, 1-yes, 2-no (Default: 2)
amsdu_force=0

# A-MPDU in TX
agg_tx=1

# TX lifetime
tx_lft=100
lp_clk_ppm=20

# # MSDU frames in A-MSDU
amsdu_maxnb=0

# 0 <= amsdu_rx_max <= 2 : Maximum A-MSDU size supported in RX
amsdu_rx_max=2

# ant diversity
ant_div=0
ap_uapsd_on=0
bfmee=1
bfmer=0
ht_on=1
ldpc_on=1

# VHT MCS: 0: MCS0_7, 1: MCS0_8, 2: MCS0_9
mcs_map=1

# HE MCS: 0:0-7, 1: 0-9, 2:0-11
he_mcs_map=1

mesh=0

murx=1
mutx=0
mutx_on=0

# Number of Spatial Streams
nss=1
phycfg=0
ps_on=0
dpsm=0
sgi=1
sgi80=0
tdls=0

# U-APSD Queues: must be seen as a bitfield
uapsd_queues=0
uapsd_timeout=0

# 20-40MHz mode
use_2040=0
# Enable 80MHz
use_80=0

# enable VHT
vht_on=1
stbc_on=1
he_ul_on=1

# enable HE
he_on=1


twt=1

# softap parameters
tx_to_vo=0
tx_to_vi=0
tx_to_be=35000
tx_to_bk=35500
