// Copyright 2020-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

/*
 * ============================================================================
 * usr_gpio_cfg.h —— User GPIO default configuration table
 * ============================================================================
 *
 * Purpose: This file defines the macro GPIO_DEFAULT_DEV_CONFIG, describing the
 *          default state of each GPIO after power-on. The driver configures it
 *          once per table during initialization (afterwards the runtime dynamic
 *          configuration takes precedence).
 *
 * Each row has 10 fields, in order and with meaning:
 *   1) gpio_id               Pin number GPIO_0 ~ GPIO_71.
 *   2) second_func_en        Whether to apply second_func_dev at power-on: ENABLE=apply the function;
 *                            DISABLE=set high-impedance (FUNC_CODE_HIGH_Z) at power-on, direction set dynamically at runtime.
 *   3) second_func_dev       Function used at power-on (only effective when second_func_en=ENABLE): peripheral (e.g.
 *                            GPIO_DEV_PWM0) or plain GPIO direction (GPIO_DEV_GPIO_OUTPUT/INPUT),
 *                            fill GPIO_DEV_INVALID for no function.
 *   4) time_sharing_func_dev Extra function for time-sharing reuse (dynamic map/unmap); not applied at power-on, only for reverse lookup by function;
 *                            fill GPIO_DEV_INVALID if not needed.
 *   5) pull_mode             Pull-up/down: GPIO_PULL_DISABLE / GPIO_PULL_UP_EN / GPIO_PULL_DOWN_EN.
 *   6) int_en                Interrupt enable: GPIO_INT_DISABLE / GPIO_INT_ENABLE.
 *   7) int_type              Trigger type: LOW_LEVEL / HIGH_LEVEL / RISING_EDGE / FALLING_EDGE.
 *   8) low_power_io_ctrl     Low-power IO behavior: DISCARD(set high-Z to prevent leakage) / KEEP_INPUT(can be a wakeup source) /
 *                            KEEP_OUTPUT(hold output level).
 *   9) driver_capacity       Drive strength: GPIO_DRIVER_CAPACITY_0 ~ _3(0 weakest, 3 strongest).
 *  10) gpio_skip             Whether to configure per this table at power-on/reset: GPIO_INIT_ENABLE=configure, DISABLE=no operation.
 *
 * Configuration rules (key points):
 *   - CP/AP each configure their own GPIOs; the same GPIO cannot be configured by multiple cores at once; unlisted GPIOs keep their power-on default state.
 *   - The peripheral function selected by second_func_dev must be legal in the chip's IO Matrix mapping, otherwise the signal cannot be output.
 *   - When used as a wakeup source: low_power_io_ctrl=KEEP_INPUT with interrupt enabled and int_type set.
 *   - For full description, examples and modification steps see the English documentation:
 *     ap/docs/bk7259/en/developer-guide/peripheral/bk_gpio.rst
 *
 * ----------------------------------------------------------------------------
 * The functions for second_func_dev fall into two categories (both defined in gpio_map.h, not user-modifiable):
 *   1) Flexible mapping GPIO_DEV_TO_IOMX_CODE_MAP: UART/SPI/I2C/PWM/I2S etc. can be assigned to any pad,
 *      not restricted to a specific GPIO number, just fill second_func_dev with the corresponding function.
 *   2) Fixed mapping MAP_FUNC_CODE_FIX_GPIO: SDIO/JPEG-DVP/RGB-LCD/QSPI/ENET/UART5/debug etc.
 *      can only land on the pads specified in the table below, see the fixed mapping table below.
 *
 * ----------------------------------------------------------------------------
 * Fixed mapping table (a 2D view derived from MAP_FUNC_CODE_FIX_GPIO in gpio_map.h, fixed per chip):
 *   SDIO/JPEG-DVP/RGB-LCD/QSPI/ENET/UART5/debug etc. functions can only land on the pads specified in the table below.
 *   Vertical axis=GPIO_ID, horizontal axis=FUNC_CODE group, cell=the function allowed for that (GPIO, FUNC_CODE)
 *   (the GPIO_DEV_ prefix is omitted, DEBUG is abbreviated as DBG, blank means undefined). To use a function, you must
 *   find it in the corresponding cell, then fill second_func_dev with GPIO_DEV_<function>; gpio_map.h is authoritative.
 *
 *   Example: JPEG_PCLK is only allowed on GPIO_29 (row GPIO_29, column 129 in the table above), i.e. fill this pin with
 *   second_func_dev=GPIO_DEV_JPEG_PCLK; if filled on a pin not listed in the table, map will return
 *   BK_ERR_GPIO_SET_INVALID_FUNC_MODE and print "GPIO device ... is not supported".
 *
 *   GPIO    126:SYS/RF  127:DEBUG 129:SDIO/JPEG    130:QSPI/ENET/UART5 131:RGB-LCD 132:ENET-alt
 *   --------------------------------------------------------------------------------------------
 *   GPIO_2  OTP_FRE_EN  DBG0      SDIO_HOST_CLK    QSPI1_CLK
 *   GPIO_3  OTP_FRE_SEL DBG1      SDIO_HOST_CMD    QSPI1_CSN
 *   GPIO_4  OTP_FRE_OUT DBG2      SDIO_HOST_DATA0  QSPI1_IO0
 *   GPIO_5              DBG3      SDIO_HOST_DATA1  QSPI1_IO1
 *   GPIO_6  CLK13M      DBG4      SDIO_HOST_DATA4  QSPI1_IO2
 *   GPIO_7  WIFI_ACTIVE DBG5      SDIO_HOST_DATA5  QSPI1_IO3
 *   GPIO_8              DBG6      SDIO_HOST_DATA6
 *   GPIO_9              DBG7      SDIO_HOST_DATA7
 *   GPIO_10                       SDIO_HOST_DATA2  CLK_AUXS
 *   GPIO_11                       SDIO_HOST_DATA3
 *   GPIO_12                       SDIO_HOST_STB
 *   GPIO_13                                                            ENET_GTCLK
 *   GPIO_14             DBG8      SDIO1_HOST_CLK                       LCD_DE      ENET_TXD3
 *   GPIO_15             DBG9      SDIO1_HOST_CMD                       LCD_VSYNC   ENET_TXD2
 *   GPIO_16             DBG10     SDIO1_HOST_DATA0                     LCD_HSYNC   ENET_TXD1
 *   GPIO_17             DBG11     SDIO1_HOST_DATA1                     LCD_DISP    ENET_TXD0
 *   GPIO_18             DBG12     SDIO1_HOST_DATA2                     LCD_CLK     CLK_AUXS_ENET
 *   GPIO_19             DBG13     SDIO1_HOST_DATA3                     LCD_B7      ENET_MDC
 *   GPIO_20                       SDIO1_HOST_DATA4                     LCD_B6      ENET_MDIO
 *   GPIO_21                       SDIO1_HOST_DATA5 ENET_REF_CLK        LCD_B5      ENET_GRCLK
 *   GPIO_22 CLK26M                SDIO1_HOST_DATA6 QSPI0_CLK           LCD_B4      ENET_RXDV
 *   GPIO_23                       SDIO1_HOST_DATA7 QSPI0_CSN           LCD_B3      ENET_RXD0
 *   GPIO_24 LPO_CLK     DBG14     SDIO1_HOST_STB   QSPI0_IO0           LCD_G7      ENET_RXD1
 *   GPIO_25             DBG15                      QSPI0_IO1           LCD_G6      ENET_RXD2
 *   GPIO_26 WIFI_TX_EN  DBG16                      QSPI0_IO2           LCD_G5      ENET_RXD3
 *   GPIO_27 FEM_LNA_EN  DBG17     CLK_AUXS_CIS     QSPI0_IO3           JPEG_MCLK
 *   GPIO_28 WIFI_RX_EN  DBG18     CLK_AUXS                                         ENET_TXEN
 *   GPIO_29             DBG19     JPEG_PCLK
 *   GPIO_30             DBG20     JPEG_HSYNC
 *   GPIO_31             DBG21     JPEG_VSYNC
 *   GPIO_32             DBG22     JPEG_PXDATA0
 *   GPIO_33             DBG23     JPEG_PXDATA1
 *   GPIO_34             DBG24     JPEG_PXDATA2
 *   GPIO_35             DBG25     JPEG_PXDATA3
 *   GPIO_36             DBG26     JPEG_PXDATA4
 *   GPIO_37             DBG27     JPEG_PXDATA5
 *   GPIO_38             DBG28     JPEG_PXDATA6
 *   GPIO_39             DBG29     JPEG_PXDATA7
 *   GPIO_40                       JPEG_PXDATA8     ENET_GTCLK          LCD_G4
 *   GPIO_41                       JPEG_PXDATA9     ENET_TXD3           LCD_G3
 *   GPIO_42             DBG30                      ENET_TXD2           LCD_G2
 *   GPIO_43             DBG31                      ENET_TXD1           LCD_R7
 *   GPIO_44                                        ENET_TXD0           LCD_R6
 *   GPIO_45                                        ENET_TXEN           LCD_R5
 *   GPIO_46                                        CLK_AUXS_ENET       LCD_R4
 *   GPIO_47                                        ENET_MDC            LCD_R3
 *   GPIO_48                                        ENET_MDIO           LCD_B2
 *   GPIO_49                       ENET_REF_CLK     ENET_GRCLK          LCD_B1
 *   GPIO_50                                        ENET_RXDV           LCD_B0
 *   GPIO_51                                        ENET_RXD0           LCD_G1
 *   GPIO_52                                        ENET_RXD1           LCD_G0
 *   GPIO_53                                        ENET_RXD2           LCD_R2
 *   GPIO_54                                        ENET_RXD3           LCD_R1
 *   GPIO_55                                        ENET_PHY_INT        LCD_R0
 *   GPIO_59                       CLK_AUXS_CIS
 *   GPIO_60                                        ENET_PHY_INT
 *   GPIO_61                       SDIO_HOST_STB
 *   GPIO_62                       SDIO_HOST_DATA7
 *   GPIO_63                       SDIO_HOST_DATA6
 *   GPIO_64                       SDIO_HOST_DATA5  UART5_RXD
 *   GPIO_65                       SDIO_HOST_DATA4  UART5_TXD
 *   GPIO_66                       SDIO_HOST_DATA3
 *   GPIO_67                       SDIO_HOST_DATA2
 *   GPIO_68                       SDIO_HOST_DATA1
 *   GPIO_69                       SDIO_HOST_DATA0
 *   GPIO_70                       SDIO_HOST_CMD
 *   GPIO_71                       SDIO_HOST_CLK
 *
 * ============================================================================
 */


#ifdef __cplusplus
extern "C" {
#endif


#if 0//CONFIG_SPE
/* GPIO0/GPIO1 are reserved for the secure-world UART1 log; keep gpio_skip as
 * GPIO_INIT_DISABLE so this core does not touch their (Secure) registers. */
#define GPIO_0_DEFAULT_MAP {GPIO_0,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2C1_SCL,        GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_DISABLE},
#define GPIO_1_DEFAULT_MAP {GPIO_1,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2C1_SDA,        GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_DISABLE},
#else
#define GPIO_0_DEFAULT_MAP
#define GPIO_1_DEFAULT_MAP
#endif

/*	 gpio_id  second_func_en           second_func_dev         time_sharing_func_dev  pull_mode        int_en            int_type                 low_power_io_ctrl                driver_capacity         gpio_skip */
#define GPIO_DEFAULT_DEV_CONFIG  \
{\
	GPIO_0_DEFAULT_MAP \
	GPIO_1_DEFAULT_MAP \
	{GPIO_2,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO_HOST_CLK,   GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_3,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO_HOST_CMD,   GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_4,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SDIO_HOST_DATA0, GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_5,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_6,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2S0_CLK,        GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_7,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2S0_SYNC,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_8,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_9,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_I2S0_DOUT,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	/* GPIO_12: ADC config pin, output pull-down to prevent ADC internal comparator charge from failing to discharge */\
	{GPIO_12, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_GPIO_OUTPUT,     GPIO_DEV_INVALID, GPIO_PULL_DOWN_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_13, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_USB0_DN,         GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_14, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_CLK,         GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_15, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_DISP,        GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_16, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_DE,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_17, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_HSYNC,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_18, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_VSYNC,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_19, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R7,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_20, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R6,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_21, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R5,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_22, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI0_CLK,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_23, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI0_CSN,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_24, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI0_IO0,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_25, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI0_IO1,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_26, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI0_IO2,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_27, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI0_IO3,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	/*{GPIO_28, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_ADC13, GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},*/\
	{GPIO_28, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2S0_MCLK,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_29, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PCLK,       GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_30, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_HSYNC,      GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_31, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_VSYNC,      GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_32, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA0,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_33, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA1,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_34, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA2,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_35, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA3,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_36, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA4,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_37, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA5,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_38, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA6,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_39, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA7,    GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE},\
	{GPIO_40, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G4,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_41, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G3,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_42, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G2,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_43, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B7,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_44, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B6,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_45, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B5,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_46, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B4,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_47, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B3,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_48, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R2,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_49, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R1,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_50, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_R0,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_51, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G1,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_52, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_G0,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_53, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B2,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_54, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B1,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_55, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_LCD_B0,          GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1, GPIO_INIT_ENABLE},\
	{GPIO_64, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_UART5_RXD,       GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
	{GPIO_65, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_UART5_TXD,       GPIO_DEV_INVALID, GPIO_PULL_UP_EN,   GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE},\
}
